// js/audit.js — extracted from index.html
// Generated by split.cjs

// ==============================
// TAB 1: FORM 3CD CLAUSES
// ==============================
var clauses=[
{number:"1-4",title:"Basic Info — Name, Address, PAN, Status",category:"basic",risk:"low",description:"Identification details of assessee.",requirements:"Verify PAN, address, legal status.",observations:["PAN name mismatch","Wrong status for LLP vs Firm"],keywords:"name address pan status"},
{number:"5",title:"Previous Year & Assessment Year",category:"basic",risk:"low",description:"Relevant PY and AY.",requirements:"Ensure correct year.",observations:["Wrong AY mentioned"],keywords:"previous year assessment year"},
{number:"6",title:"Nature of Business / Profession",category:"basic",risk:"low",description:"Business code and activities.",requirements:"Use correct IT business code.",observations:["Code not matching ITR"],keywords:"nature business profession code"},
{number:"7(a)",title:"Books of Accounts Maintained",category:"basic",risk:"medium",description:"List of books and address.",requirements:"List all books: cash book, ledger, journal, stock register.",observations:["Incomplete list","Stock register missing"],keywords:"books accounts maintained"},
{number:"7(b)",title:"Presumptive Scheme History",category:"basic",risk:"medium",description:"44AD/ADA/AE opt-out details.",requirements:"Check last 5 years. Now includes Sec 44BBC (cruise ship NR).",observations:["Historical adoption not checked"],keywords:"presumptive 44AD 44ADA 44BBC opt out"},
{number:"8",title:"Partner Profit Sharing & Tax Regime Option",category:"basic",risk:"medium",description:"Partner names, ratios, changes. Clause 8a: whether opted for 115BA/BAA/BAB/BAC/BAD/BAE.",requirements:"Verify partnership deed. Check tax regime option.",observations:["Deed not updated","115BAE not reported"],keywords:"partner profit sharing ratio 115BAE"},
{number:"9",title:"Applicability Clause & Other Audit",category:"compliance",risk:"high",description:"Which clause of 44AB applies.",requirements:"Cite correct clause.",observations:["Wrong clause cited"],keywords:"44AB applicability audit"},
{number:"10",title:"Method of Accounting",category:"financial",risk:"medium",description:"Mercantile or cash method.",requirements:"Check consistency. Companies must use mercantile.",observations:["Cash system by company"],keywords:"method accounting mercantile cash"},
{number:"11",title:"Partner Remuneration & Interest",category:"financial",risk:"high",description:"Sec 40(b) compliance.",requirements:"Verify deed. Interest max 12%. Remuneration within limits.",observations:["Exceeding 40(b) limits"],keywords:"partner salary remuneration interest 40b"},
{number:"12",title:"Presumptive Income — 44AD to 44BBC",category:"tax",risk:"high",description:"Presumptive income u/s 44AD, 44ADA, 44AE, 44AF, 44B to 44BBC.",requirements:"Now includes Sec 44BBC (cruise ship operations by NR) per Notification 23/2025.",observations:["44BBC not reported for NR cruise operators"],keywords:"presumptive 44AD 44ADA 44BBC cruise"},
{number:"13-14",title:"Scientific Research & Capital Expenditure",category:"deductions",risk:"medium",description:"Sec 35 deductions. Sec 32AC/32AD removed from AY 2025-26.",requirements:"Verify facility approval. Note: Sec 32AC, 32AD removed per Notification 23/2025.",observations:["Expenditure misclassified"],keywords:"scientific research 35 35ABA spectrum"},
{number:"15-16",title:"Inadmissible Amounts — Sec 36 & 37",category:"financial",risk:"high",description:"Capital, personal, disallowed expenses.",requirements:"Review all expenses. Sec 37(1) Expl 3 — settlement expenditure (new sub-clause iv from AY 2025-26).",observations:["Personal expenses not disallowed","CSR not identified","Settlement expenditure not checked"],keywords:"inadmissible 36 37 capital personal settlement"},
{number:"17",title:"Rates, Taxes & Cess",category:"financial",risk:"medium",description:"Non-deductible levies.",requirements:"Income tax debited to P&L.",observations:["IT not reported here"],keywords:"rates taxes cess income tax"},
{number:"18",title:"Depreciation Schedule",category:"financial",risk:"high",description:"Complete WDV schedule.",requirements:"Verify opening WDV, rates, 180-day rule. No goodwill depreciation.",observations:["Wrong rate","No depreciation on goodwill","50% rule not applied"],keywords:"depreciation WDV schedule asset"},
{number:"19",title:"Deductions — 33AB, 33ABA, 35ABA, 35ABB, 35D, 35DD, 35DDA, 35E",category:"deductions",risk:"medium",description:"Amounts admissible. Sec 32AC, 32AD removed from AY 2025-26.",requirements:"Verify amounts. 35ABA (spectrum), 35ABB (telecom licence) now included.",observations:["Spectrum/telecom costs not reported"],keywords:"33AB 35ABA spectrum telecom 35D 35DD preliminary"},
{number:"20",title:"Chapter VI-A Deductions",category:"deductions",risk:"high",description:"80C, 80D, 80G, 80IA, 80IB, 80JJAA etc.",requirements:"Verify eligibility and proofs for each deduction claimed.",observations:["No documentary evidence","80G receipts missing"],keywords:"chapter VIA deduction 80C 80D 80G 80JJAA"},
{number:"21",title:"Inadmissible under Sec 37(1) Expl + 40(a)(ia)",category:"tax",risk:"high",description:"Amounts debited to P&L disallowed. Now includes settlement expenditure (new sub-clause iv).",requirements:"Review all TDS defaults (30% disallowance). Check settlement expenditure under notified laws.",observations:["TDS not deducted on professional fees","Settlement costs not examined"],keywords:"TDS default disallowance 40a settlement"},
{number:"22",title:"MSME Payments — MSMED Act (Enhanced)",category:"compliance",risk:"high",description:"Interest to Micro/Small enterprises. Enhanced reporting per Notification 23/2025.",requirements:"Verify MSME Udyam status. Report interest inadmissible u/s 23 MSMED Act. Check 43B(h).",observations:["Vendor Udyam status not verified","Interest not computed"],keywords:"MSME MSMED interest 43B(h) Udyam"},
{number:"23",title:"Related Party — Sec 40A(2)(b)",category:"compliance",risk:"high",description:"Payments to directors, relatives.",requirements:"Compare with fair market value.",observations:["Excessive rent to director"],keywords:"related party 40A(2)(b) director"},
{number:"24",title:"Deemed Income — Sec 56(2)",category:"tax",risk:"medium",description:"Gifts and property below FMV. Sec 56(2)(viib) disclosure omitted from AY 2025-26.",requirements:"Check Sec 56(2)(x). Note: 56(2)(viib) reporting removed per Notification 23/2025.",observations:["Shares at premium not examined"],keywords:"deemed income 56(2) gift property"},
{number:"25",title:"Deemed Income — Sec 41, Balancing Charge",category:"tax",risk:"high",description:"Recovery, cessation of liability.",requirements:"Check old liabilities and asset sales.",observations:["Old liabilities not written back"],keywords:"deemed income recovery 41 balancing"},
{number:"26",title:"Section 43B — Payment Basis",category:"compliance",risk:"high",description:"GST, PF, ESI, bonus, leave encashment, MSME.",requirements:"Verify actual payment before return due date. 43B(h) for Micro/Small enterprises.",observations:["PF/ESI deposited late","MSME payment beyond 45 days"],keywords:"43B payment PF ESI GST bonus MSME"},
{number:"27",title:"TDS Disallowance & Equalisation Levy",category:"tax",risk:"high",description:"40(a)(ia) and 40(a)(ib).",requirements:"Review all TDS-applicable payments. Check equalisation levy on digital ads.",observations:["Google/Facebook ads without equalisation levy"],keywords:"TDS disallowance equalisation levy"},
{number:"30",title:"Sec 269SS/269T — Cash Loans/Deposits",category:"compliance",risk:"high",description:"Cash loans/deposits > 20,000. Note: Old Clauses 28 & 29 omitted from AY 2025-26 per Notification 23/2025.",requirements:"Scan cash book for violations. Report each transaction separately.",observations:["Cash from partners > 20,000"],keywords:"269SS 269T cash loan deposit 20000"},
{number:"31",title:"Loan/Deposit Transactions — Enhanced (AY 2025-26)",category:"compliance",risk:"high",description:"Itemized reporting with transaction codes. Major enhancement per Notification 23/2025.",requirements:"Report each loan/deposit taken/accepted/repaid with mandatory transaction codes from new dropdown. Include 269ST (cash receipt > 2L).",observations:["Transaction codes not used","Split cash receipts not aggregated"],keywords:"269ST cash 2 lakh loan deposit transaction code"},
{number:"32",title:"Sec 40A(3) — Cash > 10,000",category:"compliance",risk:"high",description:"100% disallowance of cash expenses > 10K.",requirements:"Scan cash book. Check Rule 6DD exceptions (transporters 35K).",observations:["Transporters — 35K exception not applied"],keywords:"40A(3) cash payment 10000"},
{number:"33",title:"Dividend — TDS u/s 194",category:"tax",risk:"low",description:"DDT abolished. Dividends fully taxable. TDS u/s 194.",requirements:"Verify TDS deducted on dividends paid/received.",observations:["TDS on dividend not checked"],keywords:"dividend 194 TDS"},
{number:"34",title:"TDS/TCS Compliance — CRITICAL",category:"tax",risk:"high",description:"Most scrutinized clause. Complete TDS/TCS details.",requirements:"Match 26AS/AIS. Verify rates, deposits, defaults. Check 194T (firm to partner — new).",observations:["Short deduction","Late deposit","26AS mismatch","194T not applied"],keywords:"TDS TCS 26AS compliance 194 195 194T"},
{number:"35-36",title:"Quantitative Details — Stock/Raw Material",category:"financial",risk:"medium",description:"Opening, purchase, sales, closing quantities.",requirements:"Match stock register. Check wastage.",observations:["Stock register not maintained"],keywords:"quantitative stock raw material finished goods"},
{number:"36B",title:"Share Buyback Disclosure (NEW — AY 2025-26)",category:"tax",risk:"high",description:"New clause per Notification 23/2025. Buyback u/s 2(22)(f).",requirements:"Report whether assessee received any amount under buyback, amount received, cost of acquisition of shares bought back.",observations:["Buyback amount not disclosed","Cost of acquisition not verified"],keywords:"buyback 2(22)(f) shares 36B new"},
{number:"37",title:"Pending Litigation & Demands",category:"compliance",risk:"medium",description:"Tax demands raised, refunds, appeals.",requirements:"List all pending assessments.",observations:["Pending demands not reported"],keywords:"demand refund appeal litigation"},
{number:"38-41",title:"Turnover, Cost Audit, Accounting Standards",category:"financial",risk:"high",description:"Turnover reconciliation, cost audit, AS compliance.",requirements:"Reconcile turnover with GSTR-1/3B.",observations:["Turnover mismatch","ITC differences"],keywords:"turnover GST reconciliation accounting standards cost audit"},
{number:"44",title:"GST Reconciliation — ITC",category:"compliance",risk:"high",description:"ITC availed, reversed, ineligible.",requirements:"Reconcile with GSTR-2B. Blocked credit u/s 17(5).",observations:["ITC exceeding GSTR-2B","Blocked credit claimed"],keywords:"GST ITC input tax credit GSTR-2B"}
];
function renderClauses(list){var c=document.getElementById('clauseList');if(!list.length){c.innerHTML='<p style="text-align:center;color:var(--text-light);padding:20px;">No clauses found.</p>';return;}
c.innerHTML=list.map(function(cl){var rt=cl.risk==='high'?'<span class="tag tag-high">High Risk</span>':cl.risk==='medium'?'<span class="tag tag-medium">Medium</span>':'<span class="tag tag-low">Low</span>';
return '<div class="clause-item" data-cat="'+cl.category+'"><div class="clause-header" onclick="this.parentElement.classList.toggle(\'open\')"><div style="display:flex;align-items:center;flex:1"><span class="clause-number">Cl. '+cl.number+'</span><span class="clause-title">'+cl.title+'</span></div><span class="clause-arrow">&#9660;</span></div><div class="clause-body"><div class="clause-section">'+rt+' <span class="tag tag-info">'+cl.category+'</span></div><div class="clause-section"><div class="clause-section-title">Description</div><p>'+cl.description+'</p></div><div class="clause-section"><div class="clause-section-title">What to Verify</div><p>'+cl.requirements+'</p></div><div class="clause-section"><div class="clause-section-title">Common Observations</div><ul>'+cl.observations.map(function(o){return '<li>'+o+'</li>';}).join('')+'</ul></div></div></div>';}).join('');}
function filterClauses(){var q=document.getElementById('clauseSearch').value.toLowerCase(),ab=document.querySelector('#tab-clauses .filter-btn.active'),cat=ab?ab.textContent.toLowerCase():'all';var f=clauses;if(cat!=='all')f=f.filter(function(c){return c.category===cat;});if(q)f=f.filter(function(c){return (c.title+c.description+c.keywords+c.number).toLowerCase().indexOf(q)>=0;});renderClauses(f);}
function filterCategory(cat,btn){document.querySelectorAll('#tab-clauses .filter-row:last-of-type .filter-btn').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');filterClauses();}
renderClauses(clauses);

// Form 26 — Tax Year 2026-27 onwards (IT Act 2025, Sec 63, Rule 47)
var form26Clauses=[
{number:"1-3",title:"Part A — Basic Information",category:"basic",risk:"low",description:"Name, PAN/TAN, address, status, nature of business, Tax Year.",requirements:"Verify PAN, Udyam/CIN, business code. Note: 'Tax Year' replaces PY+AY.",observations:["PAN mismatch","Wrong entity status"],keywords:"name pan address status tax year"},
{number:"4-5",title:"Audit Applicability & Books of Accounts",category:"basic",risk:"medium",description:"Sec 63 applicability (replaces 44AB). Books maintained, address.",requirements:"Cite correct clause of Sec 63. List all books including digital records.",observations:["Wrong applicability clause","Digital records not listed"],keywords:"sec 63 44AB books accounts audit applicability"},
{number:"6-7",title:"Presumptive Income & Opt-out History",category:"basic",risk:"medium",description:"Presumptive schemes opted/opted-out. Covers Sec 44AD-44BBC equivalents.",requirements:"Check last 5 years history. Includes cruise ship operations (44BBC equivalent).",observations:["Opt-out history incomplete"],keywords:"presumptive 44AD 44ADA 44BBC opt out"},
{number:"8-9",title:"Partner Details & Tax Regime Option",category:"basic",risk:"medium",description:"Partner profit sharing, remuneration, interest. Tax regime chosen.",requirements:"Verify partnership deed. Confirm new regime (default) or old regime opt-in.",observations:["Deed not updated","Regime option not declared"],keywords:"partner profit sharing tax regime 115BAC"},
{number:"10-12",title:"Method of Accounting & Prior Period Items",category:"financial",risk:"medium",description:"Mercantile/cash method. Changes in accounting policy. Prior period adjustments.",requirements:"Companies must use mercantile. Disclose policy changes with impact quantification.",observations:["Undisclosed policy change"],keywords:"accounting method mercantile cash prior period"},
{number:"13-15",title:"Depreciation Schedule (Enhanced)",category:"financial",risk:"high",description:"Complete WDV schedule with asset-wise breakup. Enhanced digital asset tracking.",requirements:"Verify opening WDV, additions, deletions, rates. 180-day rule. No goodwill depreciation. IT systems audit trail for additions.",observations:["Wrong rate applied","Goodwill depreciation claimed","IT asset trail missing"],keywords:"depreciation WDV schedule asset digital"},
{number:"16-18",title:"Inadmissible Expenditure — Capital, Personal, Disallowed",category:"financial",risk:"high",description:"Capital expenditure, personal expenses, Sec 37 disallowances. Settlement expenditure.",requirements:"Review all expenses. Check settlement expenditure under notified laws. CSR reporting enhanced.",observations:["Personal expenses not disallowed","Settlement costs not examined","CSR mismatch"],keywords:"inadmissible capital personal settlement CSR 37"},
{number:"19-21",title:"Deductions & Amounts Admissible",category:"deductions",risk:"medium",description:"All deductions claimed — scientific research, spectrum fees, preliminary expenses.",requirements:"Verify eligibility and documentary evidence for each deduction.",observations:["Missing approvals","Overclaimed amounts"],keywords:"deductions 35 35ABA spectrum preliminary"},
{number:"22-24",title:"Chapter VIII Deductions (replaces Chapter VI-A)",category:"deductions",risk:"high",description:"New section numbers for 80C-80U equivalents. Only available under old regime.",requirements:"Map each deduction to new Act section. Verify old regime opt-in if claimed.",observations:["Deductions claimed under new regime","Wrong section reference"],keywords:"chapter VIII deductions 80C 80D 80G VI-A"},
{number:"25-27",title:"MSME Payments — Enhanced Reporting",category:"compliance",risk:"high",description:"Sec 43B(h) equivalent. Udyam verification mandatory. Interest computation.",requirements:"Verify ALL vendor Udyam registrations. Report delayed payments, interest u/s MSMED Act. Transaction-level reporting.",observations:["Vendor Udyam not verified","45-day breach not reported"],keywords:"MSME MSMED 43B(h) Udyam payment"},
{number:"28-30",title:"Related Party Payments & Deemed Income",category:"compliance",risk:"high",description:"Sec 40A(2)(b) equivalent — related party. Deemed income u/s 56(2) equivalents.",requirements:"Compare with FMV. Report all related party transactions. Gift/property below FMV.",observations:["Excessive rent to director","Shares at premium not examined"],keywords:"related party 40A(2)(b) deemed income 56(2)"},
{number:"31-33",title:"Cash Transaction Reporting (Enhanced)",category:"compliance",risk:"high",description:"Cash payments >10K (Sec 40A(3) equiv), Cash loans >20K (269SS/T equiv), Cash receipts >2L (269ST equiv).",requirements:"Scan cash book comprehensively. Report each violation with transaction codes. Enhanced digital trail.",observations:["Cash splitting","Transporter exception not applied"],keywords:"cash 40A(3) 269SS 269ST 10000 20000 2 lakh"},
{number:"34-36",title:"Section 43B Equivalent — Payment Basis",category:"compliance",risk:"high",description:"GST, PF, ESI, bonus, leave encashment, MSME — payment before return due date.",requirements:"Verify actual payment dates. Cross-check with challans. MSME 45-day rule.",observations:["PF/ESI late deposit","MSME payment delayed"],keywords:"43B payment PF ESI GST bonus MSME"},
{number:"37-41",title:"Deemed Income, Recovery & Cessation",category:"tax",risk:"high",description:"Recovery of bad debts, cessation of liability (Sec 41 equiv), balancing charges.",requirements:"Check old liabilities >3 years. Asset sale profit computations.",observations:["Old liabilities not written back"],keywords:"deemed income recovery cessation 41 balancing"},
{number:"42-45",title:"Dividend, Interest & Other Income",category:"tax",risk:"medium",description:"Dividend reporting, interest income, TDS on same. Share buyback disclosure.",requirements:"Verify TDS on dividends. Report buyback u/s 2(22)(f) equivalent. Interest reconciliation.",observations:["TDS on dividend not checked","Buyback not disclosed"],keywords:"dividend interest buyback 2(22)(f) TDS"},
{number:"46-48",title:"Quantitative Details & Stock Reconciliation",category:"financial",risk:"medium",description:"Opening/closing stock, raw material consumption, finished goods. GST reconciliation.",requirements:"Match stock register with books. Reconcile with GSTR-1/3B. Report wastage.",observations:["Stock register not maintained","Turnover mismatch with GST"],keywords:"stock quantitative raw material finished goods GST reconciliation"},
{number:"49-51",title:"TDS/TCS Compliance — Transaction Level (Major Change)",category:"tax",risk:"high",description:"CRITICAL CHANGE: Transaction-level TDS/TCS reporting (not just summary). Mandatory transaction codes. Schedule TDS/TCS.",requirements:"Match EVERY transaction with 26AS/AIS/TIS. Verify rates, deposits, defaults. Transaction codes mandatory. New Sec 194T equivalent (firm→partner).",observations:["Transaction codes missing","26AS mismatch at transaction level","Short deduction"],keywords:"TDS TCS 26AS AIS transaction code compliance 194T"},
{number:"52",title:"Pending Litigation & Tax Demands",category:"compliance",risk:"medium",description:"All pending assessments, demands, appeals, refunds.",requirements:"List all pending proceedings with amounts and status.",observations:["Pending demands not reported"],keywords:"demand refund appeal litigation pending"},
{number:"53",title:"IT Systems Audit & Digital Compliance (NEW)",category:"compliance",risk:"high",description:"NEW in Form 26: IT systems audit trail, digital record integrity, accounting software details.",requirements:"Report accounting software used, version, audit trail status (mandatory from Apr 2023 for companies). Digital signature verification.",observations:["Audit trail not enabled","Software details not reported"],keywords:"IT systems audit trail digital software accounting"}
];
var activeFormGuide='2526';
function switchFYGuide(fy,btn){
document.querySelectorAll('#fyToggleRow .filter-btn').forEach(function(b){b.classList.remove('active');});
btn.classList.add('active');
activeFormGuide=fy;
document.getElementById('fyGuide2526').style.display=fy==='2526'?'block':'none';
document.getElementById('fyGuide2627').style.display=fy==='2627'?'block':'none';
document.getElementById('clauseSearch').value='';
renderClauses(fy==='2526'?clauses:form26Clauses);
}
// Override filterClauses to use active guide
var origFilterClauses=filterClauses;
filterClauses=function(){var q=document.getElementById('clauseSearch').value.toLowerCase(),ab=document.querySelector('#tab-clauses .filter-row:last-of-type .filter-btn.active'),cat=ab?ab.textContent.toLowerCase():'all';
var src=activeFormGuide==='2526'?clauses:form26Clauses;
var f=src;if(cat!=='all')f=f.filter(function(c){return c.category===cat;});if(q)f=f.filter(function(c){return (c.title+c.description+c.keywords+c.number).toLowerCase().indexOf(q)>=0;});renderClauses(f);};

// ==============================
// TAB 9: MSME TRACKER
// ==============================
function checkMSME(){var type=document.getElementById('msmeType').value,agree=document.getElementById('msmeAgree').value,inv=document.getElementById('msmeInvDate').value,pay=document.getElementById('msmePayDate').value,amt=parseFloat(document.getElementById('msmeAmt').value)||0,r=document.getElementById('msmeResult');
if(!inv||!pay){r.className='result-box applicable';r.innerHTML='<div class="result-title">Enter both dates</div>';return;}
if(type==='medium'){r.className='result-box not-applicable';r.innerHTML='<div class="result-title">Section 43B(h) does NOT apply to Medium Enterprises</div><div class="result-detail"><p>43B(h) only covers Micro and Small enterprises. No disallowance risk.</p></div>';return;}
var d1=new Date(inv),d2=new Date(pay);var days=Math.ceil((d2-d1)/(24*60*60*1000));
var limit=agree==='yes'?45:15;
var compliant=days<=limit;
r.className=compliant?'result-box not-applicable':'result-box applicable';
r.innerHTML='<div class="result-title">'+(compliant?'COMPLIANT — Payment within time':'NON-COMPLIANT — Disallowance Risk!')+'</div><div class="result-detail"><table class="limits-table" style="margin-top:10px;"><tr><th>Particulars</th><th>Details</th></tr><tr><td>Vendor Type</td><td><strong>'+type.charAt(0).toUpperCase()+type.slice(1)+' Enterprise</strong></td></tr><tr><td>Agreement</td><td>'+(agree==='yes'?'Yes (max 45 days)':'No (max 15 days)')+'</td></tr><tr><td>Time Limit</td><td><strong>'+limit+' days</strong></td></tr><tr><td>Actual Days Taken</td><td><strong>'+days+' days</strong></td></tr><tr><td>Invoice Amount</td><td>'+fmt(amt)+'</td></tr>'+(compliant?'':'<tr style="background:#fde8e8;"><td><strong>Disallowance u/s 43B(h)</strong></td><td><strong>'+fmt(amt)+'</strong></td></tr><tr><td>Excess Days</td><td>'+(days-limit)+' days late</td></tr>')+'</table></div>';}
function resetMSME(){document.getElementById('msmeInvDate').value='';document.getElementById('msmePayDate').value='';document.getElementById('msmeAmt').value='';document.getElementById('msmeResult').className='result-box';}


// ==============================
// TAB 10: IT NOTICE LAST DATE
// ==============================
function calcNotice(){var type=document.getElementById('noticeType').value,ay=document.getElementById('noticeAY').value,orderDate=document.getElementById('noticeOrderDate').value,fileDate=document.getElementById('noticeFileDate').value,r=document.getElementById('noticeResult');
if(!type){r.className='result-box';r.style.display='none';return;}
var ayStart=parseInt(ay.split('-')[0]);var ayEnd=ayStart+1;
var lastDate='',section='',explanation='',details='',fileDateInfo='';
if(fileDate){var fd=new Date(fileDate);var filingFY=fd.getMonth()>=3?fd.getFullYear():fd.getFullYear()-1;fileDateInfo='Return filed on '+fd.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+' (FY '+filingFY+'-'+(filingFY+1)+'). ';}
switch(type){
case '143_2':
section='Section 143(2)';explanation='Scrutiny Notice';
if(fileDate){var fd2=new Date(fileDate);var filingFYEnd=fd2.getMonth()>=3?fd2.getFullYear()+1:fd2.getFullYear();var sixMo=new Date(filingFYEnd,8,30);var twelveMo=new Date(filingFYEnd+1,2,31);var dueDate=new Date(ayStart,6,31);if(fd2<=dueDate){lastDate=sixMo.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});details=fileDateInfo+'Return filed within due date (31 Jul '+ayStart+'). Notice must be served within 6 months from end of FY in which return filed = 30 Sep '+filingFYEnd+'.';}else{lastDate=twelveMo.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});details=fileDateInfo+'Return filed AFTER due date. Notice must be served within 12 months from end of FY in which return filed = 31 Mar '+(filingFYEnd+1)+'.';}}else{lastDate='30 Sep '+(ayStart+1)+' (if filed by due date)';details='Enter the Date of Filing for accurate calculation. If filed by due date: 6 months from end of FY of filing. If filed late: 12 months from end of FY of filing.';}
break;
case '148':case '149_3yr':
section='Section 148/149(1)(a)';explanation='Reassessment — Within 3 Years';
lastDate='31 March '+(ayEnd+3);
details='Notice for income escaping assessment can be issued within 3 years from end of relevant AY. For AY '+ay+', relevant AY ends 31 Mar '+ayEnd+'. Last date = 31 Mar '+(ayEnd+3)+'.';
break;
case '148_50l':case '149_10yr':
section='Section 149(1)(b)';explanation='Reassessment — Beyond 3 Years (Income >50L)';
lastDate='31 March '+(ayEnd+10);
details='Where income escaping assessment amounts to Rs. 50 Lakh or more, notice can be issued within 10 years from end of relevant AY. For AY '+ay+', last date = 31 Mar '+(ayEnd+10)+'. Requires PCIT/CCIT approval. Mandatory inquiry u/s 148A before issuance.';
break;
case '154':
section='Section 154';explanation='Rectification of Mistake';
if(orderDate){var od=new Date(orderDate);od.setFullYear(od.getFullYear()+4);lastDate=od.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});}else{lastDate='4 years from date of order (enter order date above)';}
details='Rectification of mistake apparent from the record. Can be done within 4 years from the date of the order sought to be rectified. Applicable to orders u/s 143(1), 143(3), 144, 147, 154 itself, 155, 250, 254, 260A, 262.';
break;
case '263':
section='Section 263';explanation='Revision by PCIT/CIT';
if(orderDate){var od2=new Date(orderDate);od2.setFullYear(od2.getFullYear()+2);lastDate=od2.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});}else{lastDate='2 years from date of order (enter order date above)';}
details='PCIT/CIT may revise any order if it is erroneous AND prejudicial to the interest of revenue. Must be done within 2 years from date of order. Show cause notice must be given to assessee before passing revision order.';
break;
case '271B':
section='Section 271B';explanation='Penalty — Failure to Get Tax Audit';
lastDate='Before expiry of assessment limitation for AY '+ay;
details='Penalty for not getting books audited u/s 44AB. Amount = 0.5% of turnover/gross receipts OR Rs. 1,50,000, whichever is less. Penalty proceedings must be initiated before time limit for completing assessment expires. Defence: Reasonable cause u/s 273B.';
break;
}
r.className='result-box presumptive';
r.innerHTML='<div class="result-title">'+section+' — '+explanation+'</div><div class="result-detail"><table class="limits-table" style="margin-top:10px;"><tr><th>Particulars</th><th>Details</th></tr><tr><td>Assessment Year</td><td><strong>'+ay+'</strong></td></tr>'+(fileDate?'<tr><td>Date of Filing</td><td><strong>'+new Date(fileDate).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+'</strong></td></tr>':'')+'<tr style="background:#e8f8f5;"><td><strong>Last Date for Notice</strong></td><td><strong>'+lastDate+'</strong></td></tr></table><p style="margin-top:10px;font-size:0.88rem;">'+details+'</p></div>';}
function resetNotice(){document.getElementById('noticeType').value='';document.getElementById('noticeOrderDate').value='';document.getElementById('noticeFileDate').value='';document.getElementById('noticeResult').className='result-box';document.getElementById('noticeResult').style.display='none';}


// ==============================
// TAB 12: CARO 2020
// ==============================
function checkCARO(){var type=document.getElementById('caroType').value,cap=parseFloat(document.getElementById('caroCapital').value)||0,to=parseFloat(document.getElementById('caroTurnover').value)||0,borrow=document.getElementById('caroBorrow').value,r=document.getElementById('caroResult');
if(!type){r.className='result-box';return;}
var exempt=false,reason='';
if(type==='banking'){exempt=true;reason='Banking companies are exempt from CARO 2020 — regulated under Banking Regulation Act.';}
else if(type==='insurance'){exempt=true;reason='Insurance companies are exempt from CARO 2020 — regulated under Insurance Act.';}
else if(type==='section8'){exempt=true;reason='Section 8 companies (charitable) are exempt from CARO 2020.';}
else if(type==='opc'){exempt=true;reason='One Person Companies (OPC) are exempt from CARO 2020.';}
else if(type==='small'){exempt=true;reason='Small Companies u/s 2(85) are exempt from CARO 2020 (Paid-up capital ≤ 4 Cr AND Turnover ≤ 40 Cr).';}
else if(type==='private'){
if(cap<=1e7&&to<=1e8&&borrow==='no'){exempt=true;reason='Private company is exempt — Capital+Reserves ≤ 1 Cr AND Turnover ≤ 10 Cr AND Borrowings from banks/FIs ≤ 1 Cr. All 3 conditions satisfied.';}
else{exempt=false;reason='CARO 2020 APPLIES. Private company does not meet all exemption criteria:';
if(cap>1e7)reason+=' Capital+Reserves ('+fmt(cap)+') exceeds 1 Cr.';
if(to>1e8)reason+=' Turnover ('+fmt(to)+') exceeds 10 Cr.';
if(borrow==='yes')reason+=' Borrowings from banks/FIs exceed 1 Cr.';}}
else{exempt=false;reason='CARO 2020 APPLIES to '+(type==='listed'?'Listed Companies':'this company')+'. All 21 clauses must be reported upon.';}
r.className=exempt?'result-box not-applicable':'result-box applicable';
r.innerHTML='<div class="result-title">'+(exempt?'CARO 2020 — NOT APPLICABLE':'CARO 2020 — APPLICABLE')+'</div><div class="result-detail"><p>'+reason+'</p>'+(exempt?'':'<p style="margin-top:10px;">Auditor must report on all 21 clauses of CARO 2020 in the audit report.</p>')+'</div>';}
function resetCARO(){document.getElementById('caroType').value='';document.getElementById('caroCapital').value='';document.getElementById('caroTurnover').value='';document.getElementById('caroBorrow').value='no';document.getElementById('caroResult').className='result-box';}


// ==============================
// TAB 13: TAX AUDIT CHECKLIST
// ==============================
var checklistItems=[
{text:"Obtain engagement letter signed by client",cat:"prelim"},
{text:"Verify tax audit applicability — Section 44AB (turnover/receipts limits)",cat:"prelim"},
{text:"Check if Form 3CA (statutory audit exists) or 3CB (no statutory audit) applies",cat:"prelim"},
{text:"Obtain copy of previous year tax audit report",cat:"prelim"},
{text:"Collect PAN, Aadhaar, address, status, business codes",cat:"prelim"},
{text:"Verify partnership deed / LLP agreement (if applicable)",cat:"prelim"},
{text:"Confirm method of accounting — mercantile or cash",cat:"prelim"},
{text:"Verify books of account maintained — list all books (Cl. 7)",cat:"books"},
{text:"Obtain Trial Balance and financial statements",cat:"books"},
{text:"Complete bank reconciliation for all accounts",cat:"books"},
{text:"Tally cash book — verify opening and closing cash balance",cat:"books"},
{text:"Verify stock register and physical verification records",cat:"books"},
{text:"Cross-check opening balances with previous year closing",cat:"books"},
{text:"Verify all journal entries with supporting documentation",cat:"books"},
{text:"Check depreciation schedule — rates, 180-day rule, WDV (Cl. 18)",cat:"financial"},
{text:"Verify disallowances u/s 40(b) — partner salary/interest limits",cat:"financial"},
{text:"Check capital vs revenue expenditure classification",cat:"financial"},
{text:"Verify Section 43B payments — GST, PF, ESI, bonus, leave encashment (Cl. 26)",cat:"financial"},
{text:"Check MSME payments — 43B(h) compliance, verify Udyam registration",cat:"financial"},
{text:"Verify Sec 40A(3) — cash payments > 10,000, Rule 6DD exceptions (Cl. 32)",cat:"financial"},
{text:"Check Sec 40A(2)(b) — related party payments at fair value (Cl. 23)",cat:"financial"},
{text:"Verify deemed income u/s 41 — old liabilities, balancing charges (Cl. 22)",cat:"financial"},
{text:"Check quantitative details — stock, raw material, finished goods (Cl. 35-36)",cat:"financial"},
{text:"Match TDS deducted with Form 26AS / AIS (Cl. 34) — CRITICAL",cat:"compliance"},
{text:"Verify timely deposit of TDS — check for defaults and short deductions",cat:"compliance"},
{text:"Check TDS on year-end provisions — professional fees, rent, interest",cat:"compliance"},
{text:"Verify Sec 269SS/269T — cash loans/deposits > 20,000 (Cl. 28-31)",cat:"compliance"},
{text:"Check Sec 269ST — cash receipts > 2 Lakh",cat:"compliance"},
{text:"Reconcile GST returns with books — GSTR-1/3B vs turnover (Cl. 44)",cat:"compliance"},
{text:"Verify ITC claimed vs GSTR-2B — check blocked credit u/s 17(5)",cat:"compliance"},
{text:"Check Chapter VI-A deductions — 80C, 80D, 80G etc. with proofs (Cl. 21)",cat:"compliance"},
{text:"Verify presumptive scheme history — 44AD/44ADA opt-out (Cl. 7b)",cat:"compliance"},
{text:"Check pending litigation and demands — list all (Cl. 37)",cat:"compliance"},
{text:"Prepare Form 3CD — fill all clauses, report NIL where applicable",cat:"reporting"},
{text:"Cross-verify Form 3CD with ITR — turnover, income, deductions must match",cat:"reporting"},
{text:"Generate UDIN within 60 days of signing the report",cat:"reporting"},
{text:"Sign and upload Form 3CA/3CB + 3CD on Income Tax portal",cat:"reporting"},
{text:"Ensure filing before due date — 30 September of AY",cat:"reporting"},
{text:"Retain working papers and audit documentation for minimum 5 years",cat:"reporting"}
];
function renderChecklist(cat){var c=document.getElementById('checklistContainer');
var items=cat==='all'?checklistItems:checklistItems.filter(function(i){return i.cat===cat;});
var saved=JSON.parse(localStorage.getItem('rr_checklist')||'{}');
c.innerHTML=items.map(function(item,idx){var key='cl_'+checklistItems.indexOf(item);var checked=saved[key]?'checked':'';
return '<div class="checklist-item '+checked+'" onclick="toggleCheck(this,\''+key+'\')"><div class="cl-box"></div><div class="cl-text">'+item.text+'</div></div>';}).join('');
updateProgress();}
function toggleCheck(el,key){el.classList.toggle('checked');var saved=JSON.parse(localStorage.getItem('rr_checklist')||'{}');saved[key]=el.classList.contains('checked');localStorage.setItem('rr_checklist',JSON.stringify(saved));updateProgress();}
function updateProgress(){var saved=JSON.parse(localStorage.getItem('rr_checklist')||'{}');var done=Object.values(saved).filter(Boolean).length;document.getElementById('checklistProgress').textContent=done+' / '+checklistItems.length+' completed';}
function filterChecklist(cat,btn){document.querySelectorAll('#tab-auditcheck .filter-btn').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');renderChecklist(cat);}
function resetChecklist(){localStorage.removeItem('rr_checklist');renderChecklist('all');}
renderChecklist('all');


// ==============================
// AS APPLICABILITY (NCE)
// ==============================
var asData=[
{no:"AS 1",name:"Disclosure of Accounting Policies",msme:"full",detail:"Full compliance required."},
{no:"AS 2",name:"Valuation of Inventories",msme:"full",detail:"Full compliance required."},
{no:"AS 3",name:"Cash Flow Statements",msme:"exempt",detail:"Not applicable entirely for MSMEs."},
{no:"AS 4",name:"Contingencies and Events After Balance Sheet Date",msme:"full",detail:"Full compliance required."},
{no:"AS 5",name:"Net Profit or Loss, Prior Period Items, Changes in Accounting Policies",msme:"full",detail:"Full compliance required."},
{no:"AS 7",name:"Construction Contracts",msme:"full",detail:"Full compliance required."},
{no:"AS 9",name:"Revenue Recognition",msme:"full",detail:"Full compliance required."},
{no:"AS 10",name:"Property, Plant and Equipment",msme:"partial",detail:"Relaxation: May omit paragraph 87 (encouraged disclosures)."},
{no:"AS 11",name:"Effects of Changes in Foreign Exchange Rates",msme:"partial",detail:"Relaxation: May omit paragraph 44 (encouraged disclosures)."},
{no:"AS 12",name:"Accounting for Government Grants",msme:"full",detail:"Full compliance required."},
{no:"AS 13",name:"Accounting for Investments",msme:"full",detail:"Full compliance required."},
{no:"AS 14",name:"Accounting for Amalgamations",msme:"conditional",detail:"Generally not applicable unless relevant transactions exist. Apply only if amalgamation occurs."},
{no:"AS 15",name:"Employee Benefits",msme:"partial",detail:"Relaxation: May omit specific paragraphs on non-vesting compensated absences, discounting liabilities, defined benefit plans, and other long-term benefits. Alternative rational methods allowed for certain calculations."},
{no:"AS 16",name:"Borrowing Costs",msme:"full",detail:"Full compliance required."},
{no:"AS 17",name:"Segment Reporting",msme:"exempt",detail:"Not applicable entirely for MSMEs."},
{no:"AS 18",name:"Related Party Disclosures",msme:"partial",detail:"Not applicable if Turnover ≤ Rs.50 Crore, Borrowings ≤ Rs.10 Crore, and not a holding/subsidiary of another MSME. Otherwise full compliance."},
{no:"AS 19",name:"Leases",msme:"partial",detail:"Relaxation: May omit specific disclosure requirements (e.g., paras 22, 25, 37, 38, 46)."},
{no:"AS 20",name:"Earnings Per Share",msme:"exempt",detail:"Not applicable entirely for MSMEs."},
{no:"AS 21",name:"Consolidated Financial Statements",msme:"conditional",detail:"Applicable only if the entity opts or is required to prepare consolidated financial statements."},
{no:"AS 22",name:"Accounting for Taxes on Income",msme:"partial",detail:"Relaxation: Required to comply only with current tax provisions. Transitional adjustments for deferred taxes allowed."},
{no:"AS 23",name:"Accounting for Investments in Associates",msme:"conditional",detail:"Applicable only if the entity opts or is required to prepare consolidated financial statements."},
{no:"AS 24",name:"Discontinuing Operations",msme:"exempt",detail:"Not applicable entirely for MSMEs."},
{no:"AS 25",name:"Interim Financial Reporting",msme:"conditional",detail:"Applicable only if the entity opts or is required to prepare interim financial statements."},
{no:"AS 26",name:"Intangible Assets",msme:"partial",detail:"Relaxation: May omit specific disclosure paragraphs (e.g., paras 90(d)(iii), 90(d)(iv), 98)."},
{no:"AS 27",name:"Financial Reporting of Interests in Joint Ventures",msme:"conditional",detail:"Generally not applicable unless relevant transactions (jointly controlled operations/assets) exist."},
{no:"AS 28",name:"Impairment of Assets",msme:"partial",detail:"Relaxation: May estimate 'value in use' without present value technique. Specific disclosure relaxations allowed (e.g., paras 121(c)(ii), 121(d), 123)."},
{no:"AS 29",name:"Provisions, Contingent Liabilities and Contingent Assets",msme:"partial",detail:"Relaxation: May omit disclosure paragraphs 66 and 67."}
];
var asTags={full:'<span class="tag tag-low">Full Compliance</span>',exempt:'<span class="tag tag-high">Not Applicable</span>',partial:'<span class="tag tag-medium">Partial Relaxation</span>',conditional:'<span class="tag tag-info">Conditional</span>'};
function renderASTable(list,containerId){var c=document.getElementById(containerId);
c.innerHTML='<table class="limits-table"><thead><tr><th style="width:60px;">AS No.</th><th>Standard</th><th style="width:130px;">MSME Status</th><th>Details for MSMEs</th></tr></thead><tbody>'+list.map(function(a){
var bg=a.msme==='exempt'?'#fde8e8':a.msme==='partial'?'#fef9e7':a.msme==='conditional'?'#eaf2f8':'';
return '<tr'+(bg?' style="background:'+bg+'"':'')+'><td><strong>'+a.no+'</strong></td><td>'+a.name+'</td><td>'+asTags[a.msme]+'</td><td style="font-size:0.85rem;">'+a.detail+'</td></tr>';}).join('')+'</tbody></table>';}
function filterAS(cat,btn){document.querySelectorAll('#asFullListCard .filter-btn').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');renderASTable(cat==='all'?asData:asData.filter(function(a){return a.msme===cat;}),'asFullTableContainer');}
function filterASResult(cat,btn){document.querySelectorAll('#asExemptionCard .filter-btn').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');var rel=asData.filter(function(a){return a.msme!=='full';});if(cat!=='all')rel=rel.filter(function(a){return a.msme===cat;});renderASTable(rel,'asTableContainer');}
function checkASClassification(){
var listed=document.getElementById('asListed').value==='yes';
var bfi=document.getElementById('asBFI').value==='yes';
var turnover=parseFloat(document.getElementById('asTurnover').value)||0;
var borrowing=parseFloat(document.getElementById('asBorrowing').value)||0;
var holding=document.getElementById('asHolding').value==='yes';
var twoYear=document.getElementById('as2Year').value==='yes';
var r=document.getElementById('asClassResult');
var reasons=[];
if(listed)reasons.push('Equity/debt instruments are listed or in process of listing');
if(bfi)reasons.push('Entity is a Bank / Financial Institution / Insurance Company');
if(turnover>250)reasons.push('Turnover (₹'+turnover+' Cr) exceeds ₹250 Crore');
if(borrowing>50)reasons.push('Borrowings (₹'+borrowing+' Cr) exceed ₹50 Crore');
if(holding)reasons.push('Entity is a Holding/Subsidiary of a Non-MSME entity');
var isMSME=reasons.length===0;
if(isMSME&&!twoYear){
r.className='result-box applicable';
r.innerHTML='<div class="result-title">⏳ Potentially MSME — But 2-Year Rule Applies</div><div class="result-detail"><p>The entity meets all MSME criteria <strong>this year</strong>, but has not yet met them for <strong>two consecutive years</strong>.</p><p style="margin-top:8px;">As per ICAI rules, MSME exemptions are available only after meeting all criteria for two consecutive accounting periods. The entity must comply as a <strong>Large Entity</strong> until the 2-year condition is satisfied.</p><p style="margin-top:8px;"><strong>Action:</strong> Continue with full AS compliance this year. Track status for next year.</p></div>';
document.getElementById('asExemptionCard').style.display='none';
document.getElementById('asFullListCard').style.display='block';
renderASTable(asData,'asFullTableContainer');
}else if(isMSME){
var exemptCount=asData.filter(function(a){return a.msme==='exempt';}).length;
var partialCount=asData.filter(function(a){return a.msme==='partial';}).length;
var condCount=asData.filter(function(a){return a.msme==='conditional';}).length;
r.className='result-box presumptive';
r.innerHTML='<div class="result-title">✅ MSME Entity — Exemptions Available</div><div class="result-detail"><p>The entity qualifies as an <strong>MSME (Micro, Small & Medium Entity)</strong> under ICAI classification.</p><table class="limits-table" style="margin-top:10px;"><tr><td>Fully Exempt AS</td><td><strong>'+exemptCount+'</strong> standards (not applicable at all)</td></tr><tr><td>Partial Relaxation</td><td><strong>'+partialCount+'</strong> standards (specific para exemptions)</td></tr><tr><td>Conditional</td><td><strong>'+condCount+'</strong> standards (apply only if relevant transactions exist)</td></tr></table><p style="margin-top:10px;"><strong>Note:</strong> Entity must disclose in financial statements that MSME exemptions have been availed.</p></div>';
document.getElementById('asExemptionCard').style.display='block';
document.getElementById('asFullListCard').style.display='block';
var relAS=asData.filter(function(a){return a.msme!=='full';});
renderASTable(relAS,'asTableContainer');
renderASTable(asData,'asFullTableContainer');
}else{
r.className='result-box not-applicable';
r.innerHTML='<div class="result-title">❌ Large Entity — Full Compliance Required</div><div class="result-detail"><p>The entity does <strong>NOT</strong> qualify as MSME. Reasons:</p><ul style="margin:8px 0 0 20px;">'+reasons.map(function(x){return '<li>'+x+'</li>';}).join('')+'</ul><p style="margin-top:10px;"><strong>All 27 Accounting Standards must be complied with fully.</strong> No exemptions or relaxations are available.</p></div>';
document.getElementById('asExemptionCard').style.display='none';
document.getElementById('asFullListCard').style.display='block';
renderASTable(asData,'asFullTableContainer');
}}
function resetASChecker(){document.getElementById('asListed').value='no';document.getElementById('asBFI').value='no';document.getElementById('asTurnover').value='';document.getElementById('asBorrowing').value='';document.getElementById('asHolding').value='no';document.getElementById('as2Year').value='yes';document.getElementById('asClassResult').className='result-box';document.getElementById('asClassResult').innerHTML='';document.getElementById('asExemptionCard').style.display='none';document.getElementById('asFullListCard').style.display='none';}


