// js/calculators.js — extracted from index.html
// Generated by split.cjs

// ==============================
// EMI CALCULATOR
// ==============================
var emiState=null;
function round2(n){return Math.round((n+Number.EPSILON)*100)/100;}
function calculateEMI(){
var loan=parseFloat(document.getElementById('emiLoanAmount').value)||0;
var annualRate=parseFloat(document.getElementById('emiAnnualRate').value)||0;
var tenor=parseFloat(document.getElementById('emiTenor').value)||0;
var tenorUnit=document.getElementById('emiTenorUnit').value;
var rateType=document.getElementById('emiRateType').value;
var result=document.getElementById('emiResult');
if(loan<=0||tenor<=0){result.className='result-box applicable';result.innerHTML='<div class="result-title">Please enter loan amount and installment tenor.</div>';return;}
if(annualRate<0){result.className='result-box applicable';result.innerHTML='<div class="result-title">Annual interest rate cannot be negative.</div>';return;}
var months=Math.round(tenorUnit==='years'?tenor*12:tenor);
if(months<=0){result.className='result-box applicable';result.innerHTML='<div class="result-title">Installment tenor must be at least 1 month.</div>';return;}
var monthlyRate=annualRate/12/100;
var schedule=[];
var emi=0,totalInterest=0,totalPayment=0,balance=loan;
if(rateType==='reducing'){
emi=monthlyRate===0?loan/months:(loan*monthlyRate*Math.pow(1+monthlyRate,months))/(Math.pow(1+monthlyRate,months)-1);
for(var i=1;i<=months;i++){
var opening=balance;
var interest=monthlyRate===0?0:opening*monthlyRate;
var principal=emi-interest;
if(i===months){principal=opening;emi=principal+interest;}
balance=Math.max(0,opening-principal);
interest=round2(interest);principal=round2(principal);emi=round2(emi);balance=round2(balance);
totalInterest+=interest;totalPayment+=emi;
schedule.push({no:i,opening:round2(opening),emi:emi,interest:interest,principal:principal,closing:balance});
}
}else{
var flatInterest=loan*(annualRate/100)*(months/12);
emi=(loan+flatInterest)/months;
var fixedInterest=flatInterest/months;
var principalPart=loan/months;
for(var j=1;j<=months;j++){
var openBal=balance;
var principalFlat=j===months?openBal:principalPart;
var interestFlat=annualRate===0?0:fixedInterest;
var emiFlat=principalFlat+interestFlat;
balance=Math.max(0,openBal-principalFlat);
interestFlat=round2(interestFlat);principalFlat=round2(principalFlat);emiFlat=round2(emiFlat);balance=round2(balance);
totalInterest+=interestFlat;totalPayment+=emiFlat;
schedule.push({no:j,opening:round2(openBal),emi:emiFlat,interest:interestFlat,principal:principalFlat,closing:balance});
}
emi=schedule.length?schedule[0].emi:0;
}
totalInterest=round2(totalInterest);
totalPayment=round2(totalPayment);
emiState={loan:round2(loan),annualRate:annualRate,months:months,tenor:tenor,tenorUnit:tenorUnit,rateType:rateType,emi:round2(emi),totalInterest:totalInterest,totalPayment:totalPayment,schedule:schedule};
result.className='result-box presumptive';
result.innerHTML='<div class="result-title">EMI Schedule Generated</div>'+
'<div class="stats-row" style="margin-top:14px;">'+
'<div class="stat-card"><div class="stat-number">Rs '+fmt(emiState.emi)+'</div><div class="stat-label">Monthly EMI</div></div>'+
'<div class="stat-card"><div class="stat-number">Rs '+fmt(emiState.totalInterest)+'</div><div class="stat-label">Total Interest</div></div>'+
'<div class="stat-card"><div class="stat-number">Rs '+fmt(emiState.totalPayment)+'</div><div class="stat-label">Total Payment</div></div>'+
'<div class="stat-card"><div class="stat-number">'+fmt(emiState.months)+'</div><div class="stat-label">Installments</div></div>'+
'</div>'+
'<div class="result-detail"><p><strong>Rate Type:</strong> '+(rateType==='reducing'?'Reducing Balance':'Fixed / Flat Rate')+' | <strong>Loan Amount:</strong> Rs '+fmt(emiState.loan)+' | <strong>Annual Interest:</strong> '+annualRate+'%</p>'+
'<div class="table-scroll"><table class="limits-table"><thead><tr><th>No.</th><th>Opening Balance</th><th>EMI</th><th>Interest</th><th>Principal</th><th>Closing Balance</th></tr></thead><tbody>'+
schedule.map(function(row){return '<tr><td>'+row.no+'</td><td>Rs '+fmt(row.opening)+'</td><td>Rs '+fmt(row.emi)+'</td><td>Rs '+fmt(row.interest)+'</td><td>Rs '+fmt(row.principal)+'</td><td>Rs '+fmt(row.closing)+'</td></tr>';}).join('')+
'</tbody></table></div></div>';
}
function resetEMI(){
['emiLoanAmount','emiAnnualRate','emiTenor'].forEach(function(id){document.getElementById(id).value='';});
document.getElementById('emiTenorUnit').value='years';
document.getElementById('emiRateType').value='reducing';
document.getElementById('emiResult').className='result-box';
document.getElementById('emiResult').innerHTML='';
emiState=null;
}
function downloadEMIPDF(){
if(!emiState){alert('Generate the EMI schedule first.');return;}
if(!window.jspdf||!window.jspdf.jsPDF){alert('PDF library could not be loaded. Please check your internet connection and try again.');return;}
var jsPDF=window.jspdf.jsPDF;
var doc=new jsPDF({orientation:'landscape',unit:'pt',format:'a4'});
doc.setFontSize(16);
doc.text('EMI Schedule',40,40);
doc.setFontSize(10);
doc.text('Loan Amount: Rs '+fmt(emiState.loan),40,65);
doc.text('Annual Interest Rate: '+emiState.annualRate+'%',220,65);
doc.text('Rate Type: '+(emiState.rateType==='reducing'?'Reducing Balance':'Fixed / Flat Rate'),420,65);
doc.text('Installments: '+emiState.months,40,82);
doc.text('Monthly EMI: Rs '+fmt(emiState.emi),220,82);
doc.text('Total Interest: Rs '+fmt(emiState.totalInterest),420,82);
doc.text('Total Payment: Rs '+fmt(emiState.totalPayment),620,82);
if(doc.autoTable){
doc.autoTable({
startY:100,
head:[['No.','Opening Balance','EMI','Interest','Principal','Closing Balance']],
body:emiState.schedule.map(function(row){return [String(row.no),'Rs '+fmt(row.opening),'Rs '+fmt(row.emi),'Rs '+fmt(row.interest),'Rs '+fmt(row.principal),'Rs '+fmt(row.closing)];}),
styles:{fontSize:8,cellPadding:4},
headStyles:{fillColor:[32,58,67]},
alternateRowStyles:{fillColor:[248,255,254]},
margin:{left:30,right:30}
});
}
doc.save('emi-schedule.pdf');
}

// ==============================
// TAB 3: IT CALCULATOR
// ==============================
function calcOldTax(income,age){var ex=age==='above80'?500000:age==='60to80'?300000:250000;if(income<=ex)return 0;var tax=0;if(income>1000000)tax+=(income-1000000)*0.3;if(income>500000)tax+=Math.min(income-500000,500000)*0.2;if(income>ex)tax+=Math.min(income-ex,500000-ex)*0.05;return Math.max(tax,0);}
function calcNewTax(income){if(income<=400000)return 0;var tax=0;var slabs=[[400000,0.05],[400000,0.10],[400000,0.15],[400000,0.20],[400000,0.25],[Infinity,0.30]];var rem=income-400000;for(var i=0;i<slabs.length&&rem>0;i++){var amt=Math.min(rem,slabs[i][0]);tax+=amt*slabs[i][1];rem-=amt;}return tax;}
function calculateIT(){var gross=parseFloat(document.getElementById('itGross').value)||0,age=document.getElementById('itAge').value,ded=parseFloat(document.getElementById('itDeductions').value)||0,std=parseFloat(document.getElementById('itStdDed').value)||0,r=document.getElementById('itResult');
if(!gross){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please enter income</div>';return;}
var oldIncome=Math.max(gross-std-ded,0),newIncome=Math.max(gross-std,0);
var oldTax=calcOldTax(oldIncome,age),newTax=calcNewTax(newIncome);
if(oldIncome<=500000)oldTax=0;if(newIncome<=1200000)newTax=0;
var oldCess=oldTax*0.04,newCess=newTax*0.04;
var oldTotal=Math.round(oldTax+oldCess),newTotal=Math.round(newTax+newCess);
var better=oldTotal<=newTotal?'Old Regime':'New Regime',saving=Math.abs(oldTotal-newTotal);
r.className='result-box presumptive';
r.innerHTML='<div class="result-title">'+better+' saves you '+fmt(saving)+' more</div><div class="result-detail"><table class="limits-table" style="margin-top:10px;"><tr><th></th><th>Old Regime</th><th>New Regime</th></tr><tr><td>Gross Income</td><td>'+fmt(gross)+'</td><td>'+fmt(gross)+'</td></tr><tr><td>Std Deduction</td><td>'+fmt(std)+'</td><td>'+fmt(std)+'</td></tr><tr><td>Ch VI-A Deductions</td><td>'+fmt(ded)+'</td><td>N/A</td></tr><tr><td>Taxable Income</td><td><strong>'+fmt(oldIncome)+'</strong></td><td><strong>'+fmt(newIncome)+'</strong></td></tr><tr><td>Tax</td><td>'+fmt(Math.round(oldTax))+'</td><td>'+fmt(Math.round(newTax))+'</td></tr><tr><td>Cess (4%)</td><td>'+fmt(Math.round(oldCess))+'</td><td>'+fmt(Math.round(newCess))+'</td></tr><tr style="background:#e8f8f5;"><td><strong>Total Tax</strong></td><td><strong>'+fmt(oldTotal)+'</strong></td><td><strong>'+fmt(newTotal)+'</strong></td></tr></table></div>';}
function resetIT(){['itGross','itDeductions'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('itResult').className='result-box';}



// ==============================
// TAB 7: DEPRECIATION (IT)
// ==============================
function updateDepRate(){var v=document.getElementById('depAsset').value,inp=document.getElementById('depRate');if(v&&v!=='custom'){inp.value=parseInt(v);}}
function calcDep(){var rate=parseFloat(document.getElementById('depRate').value)||0,wdv=parseFloat(document.getElementById('depWDV').value)||0,add=parseFloat(document.getElementById('depAdd').value)||0,del=parseFloat(document.getElementById('depDel').value)||0,half=document.getElementById('dep180').value,r=document.getElementById('depResult');
if(!rate||(!wdv&&!add)){r.className='result-box applicable';r.innerHTML='<div class="result-title">Enter asset details</div>';return;}
var base=wdv+add-del;if(base<0)base=0;
var effectiveRate=half==='no'?rate/2:rate;
var dep=Math.round(base*effectiveRate/100);var closing=base-dep;
r.className='result-box presumptive';
r.innerHTML='<div class="result-title">Depreciation: '+fmt(dep)+'</div><div class="result-detail"><table class="limits-table" style="margin-top:10px;"><tr><th>Particulars</th><th>Amount</th></tr><tr><td>Opening WDV</td><td>'+fmt(wdv)+'</td></tr><tr><td>(+) Additions</td><td>'+fmt(add)+'</td></tr><tr><td>(-) Deletions/Sale</td><td>'+fmt(del)+'</td></tr><tr><td>Base for Depreciation</td><td><strong>'+fmt(base)+'</strong></td></tr><tr><td>Rate Applied</td><td>'+effectiveRate+'%'+(half==='no'?' (50% of '+rate+'%)':'')+'</td></tr><tr style="background:#e8f8f5;"><td><strong>Depreciation</strong></td><td><strong>'+fmt(dep)+'</strong></td></tr><tr><td><strong>Closing WDV</strong></td><td><strong>'+fmt(closing)+'</strong></td></tr></table></div>';}
function resetDep(){['depRate','depWDV','depAdd','depDel'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('depAsset').value='';document.getElementById('depResult').className='result-box';}

// ==============================
// TAB 8: DEPRECIATION (Companies Act)
// ==============================
function updateDepCoRate(){var v=document.getElementById('depCoAsset').value;if(v&&v!=='custom_co'){var parts=v.split('_');document.getElementById('depCoLife').value=parts[1];}}
function calcDepCo(){var cost=parseFloat(document.getElementById('depCoCost').value)||0,life=parseFloat(document.getElementById('depCoLife').value)||0,residual=parseFloat(document.getElementById('depCoResidual').value)||5,dateStr=document.getElementById('depCoDate').value,yeStr=document.getElementById('depCoYearEnd').value,r=document.getElementById('depCoResult');
if(!cost||!life){r.className='result-box applicable';r.innerHTML='<div class="result-title">Enter cost and useful life</div>';return;}
var residualVal=Math.round(cost*residual/100);var depBase=cost-residualVal;
var annualDep=Math.round(depBase/life);
var slmRate=((100-residual)/life).toFixed(2);
var days=365,propDep=annualDep;
if(dateStr&&yeStr){var d1=new Date(dateStr),d2=new Date(yeStr);if(d1<d2){days=Math.ceil((d2-d1)/(24*60*60*1000));if(days>365)days=365;propDep=Math.round(annualDep*days/365);}}
r.className='result-box presumptive';
r.innerHTML='<div class="result-title">Annual Depreciation (SLM): '+fmt(annualDep)+'</div><div class="result-detail"><table class="limits-table" style="margin-top:10px;"><tr><th>Particulars</th><th>Amount</th></tr><tr><td>Cost of Asset</td><td>'+fmt(cost)+'</td></tr><tr><td>Residual Value ('+residual+'%)</td><td>'+fmt(residualVal)+'</td></tr><tr><td>Depreciable Amount</td><td><strong>'+fmt(depBase)+'</strong></td></tr><tr><td>Useful Life</td><td>'+life+' years</td></tr><tr><td>SLM Rate</td><td>'+slmRate+'%</td></tr><tr style="background:#e8f8f5;"><td><strong>Annual Depreciation</strong></td><td><strong>'+fmt(annualDep)+'</strong></td></tr>'+(days<365?'<tr><td>Days Used in Year</td><td>'+days+' / 365</td></tr><tr style="background:#fff3e0;"><td><strong>Proportionate Depreciation</strong></td><td><strong>'+fmt(propDep)+'</strong></td></tr>':'')+'</table></div>';}
function resetDepCo(){['depCoCost','depCoLife'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('depCoAsset').value='';document.getElementById('depCoResidual').value='5';document.getElementById('depCoDate').value='';document.getElementById('depCoResult').className='result-box';}


// ==============================
// CAPITAL GAINS CALCULATOR
// ==============================
var ciiTable={'2001-02':100,'2002-03':105,'2003-04':109,'2004-05':113,'2005-06':117,'2006-07':122,'2007-08':129,'2008-09':137,'2009-10':148,'2010-11':167,'2011-12':184,'2012-13':200,'2013-14':220,'2014-15':240,'2015-16':254,'2016-17':264,'2017-18':272,'2018-19':280,'2019-20':289,'2020-21':301,'2021-22':317,'2022-23':331,'2023-24':348,'2024-25':363,'2025-26':376};
function getCII(dateStr){
if(!dateStr)return 0;
var d=new Date(dateStr);var y=d.getFullYear();var m=d.getMonth();
var fy=m>=3?y+'-'+(''+(y+1)).slice(2):((y-1)+'-'+((''+y).slice(2)));
return ciiTable[fy]||0;
}
function getHoldingMonths(buyDate,sellDate){
if(!buyDate||!sellDate)return 0;
var b=new Date(buyDate),s=new Date(sellDate);
return (s.getFullYear()-b.getFullYear())*12+(s.getMonth()-b.getMonth());
}
function getLTCGThreshold(asset){
if(asset==='listed_eq'||asset==='equity_mf')return 12;
if(asset==='debt_mf'||asset==='unlisted'||asset==='property'||asset==='gold')return 24;
return 36;
}
function updateCGFields(){
var a=document.getElementById('cgAsset').value;
var buyDate=document.getElementById('cgDateBuy').value;
var sellDate=document.getElementById('cgDateSell').value;
var isProperty=a==='property';
var isPropertyBeforeJul24=false;
if(isProperty&&buyDate){isPropertyBeforeJul24=new Date(buyDate)<new Date('2024-07-23');}
var showCII=isPropertyBeforeJul24;
var showFMV=(a==='listed_eq'||a==='equity_mf')&&buyDate&&new Date(buyDate)<new Date('2018-01-31');
showFMV=showFMV||isPropertyBeforeJul24;
document.getElementById('cgCIIBuyGrp').style.display=showCII?'block':'none';
document.getElementById('cgCIISellGrp').style.display=showCII?'block':'none';
document.getElementById('cgCIIImpGrp').style.display=showCII?'block':'none';
document.getElementById('cgFMVGrp').style.display=showFMV?'block':'none';
document.getElementById('cgImpDateGrp').style.display=isProperty?'block':'none';
// Auto-populate CII
if(showCII){
var ciiBuy=getCII(buyDate);if(ciiBuy)document.getElementById('cgCIIBuy').value=ciiBuy;
var ciiSell=getCII(sellDate);if(ciiSell)document.getElementById('cgCIISell').value=ciiSell;
var impDate=document.getElementById('cgDateImprovement').value;
if(impDate){var ciiImp=getCII(impDate);if(ciiImp)document.getElementById('cgCIIImp').value=ciiImp;}
}
// FMV label
if(showFMV){
if(isPropertyBeforeJul24)document.getElementById('cgFMVLabel').textContent='FMV as on 23.07.2024 / Stamp Duty Value Rs.';
else document.getElementById('cgFMVLabel').textContent='FMV as on 31.01.2018 Rs.';
}
// Auto holding period
if(a&&buyDate&&sellDate){
var months=getHoldingMonths(buyDate,sellDate);
var threshold=getLTCGThreshold(a);
var isLong=months>threshold;
var thresholdLabel=threshold===12?'12 months':threshold===24?'24 months':'36 months';
document.getElementById('cgHoldingText').value=months+' months — '+(isLong?'LONG TERM (>'+thresholdLabel+')':'SHORT TERM (≤'+thresholdLabel+')');
document.getElementById('cgHoldingText').style.color=isLong?'#00b894':'#d63031';
document.getElementById('cgHoldingText').style.fontWeight='700';
}else{
document.getElementById('cgHoldingText').value='Select asset & enter dates';
document.getElementById('cgHoldingText').style.color='';document.getElementById('cgHoldingText').style.fontWeight='';
}
}
function calcCapGain(){
var a=document.getElementById('cgAsset').value;
var buyDate=document.getElementById('cgDateBuy').value;
var sellDate=document.getElementById('cgDateSell').value;
var cost=parseFloat(document.getElementById('cgCost').value)||0;
var sale=parseFloat(document.getElementById('cgSale').value)||0;
var exp=parseFloat(document.getElementById('cgExpense').value)||0;
var imp=parseFloat(document.getElementById('cgImprovement').value)||0;
var r=document.getElementById('cgResult');
if(!a){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please select an asset type</div>';return;}
if(!buyDate||!sellDate){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please enter both purchase and sale dates</div>';return;}
if(!sale){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please enter sale price</div>';return;}
var months=getHoldingMonths(buyDate,sellDate);
var threshold=getLTCGThreshold(a);
var isLong=months>threshold;
var h=isLong?'long':'short';
var netSale=sale-exp;
var adjCost=cost;
var adjImp=imp;
var gain=0,tax=0,rate='',method='',exemption=0;
var isPropertyBeforeJul24=a==='property'&&new Date(buyDate)<new Date('2024-07-23');
if(isLong){
rate='12.5%';
if(isPropertyBeforeJul24){
var ciiBuy=parseFloat(document.getElementById('cgCIIBuy').value)||getCII(buyDate)||100;
var ciiSell=parseFloat(document.getElementById('cgCIISell').value)||getCII(sellDate)||376;
var ciiImp=parseFloat(document.getElementById('cgCIIImp').value)||0;
var impDate=document.getElementById('cgDateImprovement').value;
if(!ciiImp&&impDate)ciiImp=getCII(impDate);
var indexedCost=Math.round(cost*(ciiSell/ciiBuy));
var indexedImp=ciiImp?Math.round(imp*(ciiSell/ciiImp)):imp;
var totalIndexed=indexedCost+indexedImp;
var totalPlain=cost+imp;
var gainNoIndex=netSale-totalPlain;
var gainWithIndex=netSale-totalIndexed;
var taxNoIndex=Math.round(Math.max(gainNoIndex,0)*0.125);
var taxWithIndex=Math.round(Math.max(gainWithIndex,0)*0.20);
var better=taxNoIndex<=taxWithIndex?'without':'with';
var chosenTax=Math.min(taxNoIndex,taxWithIndex);
r.className='result-box presumptive';
r.innerHTML='<div class="result-title">LTCG on Property (Grandfathered — Acquired before 23.07.2024)</div><div class="result-detail"><p style="margin-bottom:8px;"><strong>Holding Period:</strong> '+months+' months (LTCG threshold: >24 months)</p><table class="limits-table" style="margin-top:10px;"><tr><th></th><th>Option A: Without Indexation</th><th>Option B: With Indexation</th></tr><tr><td>Sale Consideration</td><td>'+fmt(netSale)+'</td><td>'+fmt(netSale)+'</td></tr><tr><td>Cost of Acquisition</td><td>'+fmt(cost)+'</td><td>'+fmt(indexedCost)+' (CII: '+ciiBuy+'→'+ciiSell+')</td></tr>'+(imp?'<tr><td>Cost of Improvement</td><td>'+fmt(imp)+'</td><td>'+fmt(indexedImp)+(ciiImp?' (CII: '+ciiImp+'→'+ciiSell+')':' (no date)')+'</td></tr>':'')+'<tr><td>Total Deduction</td><td>'+fmt(totalPlain)+'</td><td>'+fmt(totalIndexed)+'</td></tr><tr><td>Capital Gain</td><td><strong>'+fmt(gainNoIndex)+'</strong></td><td><strong>'+fmt(gainWithIndex)+'</strong></td></tr><tr><td>Tax Rate</td><td>12.5%</td><td>20%</td></tr><tr style="background:#e8f8f5;"><td><strong>Tax Payable</strong></td><td><strong>Rs '+fmt(taxNoIndex)+'</strong></td><td><strong>Rs '+fmt(taxWithIndex)+'</strong></td></tr></table><div style="background:#e8f8f5;padding:12px;border-radius:8px;margin-top:12px;"><strong>✅ Better Option: '+better.charAt(0).toUpperCase()+better.slice(1)+' Indexation</strong><br>Tax: Rs '+fmt(chosenTax)+' + Cess (4%): Rs '+fmt(Math.round(chosenTax*0.04))+' = <strong>Rs '+fmt(Math.round(chosenTax*1.04))+'</strong><br><span style="font-size:0.82rem;">Exemptions u/s 54/54EC/54F may further reduce tax.</span></div></div>';
return;
}
if(a==='listed_eq'||a==='equity_mf'){
var fmv2=parseFloat(document.getElementById('cgFMV').value)||0;
if(fmv2>0&&new Date(buyDate)<new Date('2018-01-31'))adjCost=Math.max(Math.min(fmv2,netSale),cost);
exemption=125000;
}
gain=netSale-(adjCost+adjImp);
var taxableGain=Math.max(gain-exemption,0);
tax=Math.round(taxableGain*0.125);
method='LTCG @ 12.5%'+(exemption?' (after Rs 1.25L exemption)':'');
}else{
gain=netSale-(adjCost+adjImp);
if(a==='listed_eq'||a==='equity_mf'){rate='20%';tax=Math.round(Math.max(gain,0)*0.20);method='STCG @ 20% (Sec 111A)';}
else{rate='Slab Rate';tax=0;method='STCG — Taxable at your slab rate';}
}
var cess=Math.round(tax*0.04);
r.className=gain>0?'result-box not-applicable':'result-box presumptive';
r.innerHTML='<div class="result-title">'+(gain>0?'Capital Gain: Rs '+fmt(gain):'Capital Loss: Rs '+fmt(Math.abs(gain)))+'</div><div class="result-detail"><p style="margin-bottom:8px;"><strong>Holding Period:</strong> '+months+' months — <strong>'+(isLong?'LONG TERM':'SHORT TERM')+'</strong></p><table class="limits-table" style="margin-top:10px;"><tr><td>Net Sale Consideration</td><td><strong>'+fmt(netSale)+'</strong></td></tr><tr><td>Cost of Acquisition</td><td>'+fmt(adjCost)+'</td></tr>'+(adjImp?'<tr><td>Cost of Improvement</td><td>'+fmt(adjImp)+'</td></tr>':'')+(exemption?'<tr><td>Annual Exemption (Sec 112A)</td><td>(-) '+fmt(exemption)+'</td></tr>':'')+'<tr><td>'+(isLong?'Long':'Short')+' Term Capital Gain</td><td><strong>'+fmt(gain)+'</strong></td></tr><tr><td>Tax Rate</td><td>'+method+'</td></tr><tr style="background:#e8f8f5;"><td><strong>Tax on Capital Gain</strong></td><td><strong>Rs '+fmt(tax)+'</strong></td></tr>'+(tax?'<tr><td>+ Cess (4%)</td><td>Rs '+fmt(cess)+'</td></tr><tr><td><strong>Total Tax</strong></td><td><strong>Rs '+fmt(tax+cess)+'</strong></td></tr>':'')+'</table>'+(rate==='Slab Rate'?'<p style="margin-top:8px;font-size:0.85rem;">STCG of Rs '+fmt(gain)+' will be added to your total income and taxed at applicable slab rate.</p>':'')+'</div>';
}
function resetCG(){['cgCost','cgSale','cgExpense','cgImprovement','cgCIIBuy','cgCIISell','cgCIIImp','cgFMV','cgDateBuy','cgDateSell','cgDateImprovement'].forEach(function(id){var el=document.getElementById(id);if(el)el.value='';});document.getElementById('cgAsset').value='';document.getElementById('cgResult').className='result-box';document.getElementById('cgResult').innerHTML='';document.getElementById('cgHoldingText').value='';document.getElementById('cgHoldingText').style.color='';updateCGFields();}

// ==============================
// CAPITAL GAINS EXEMPTION PLANNER (Sec 54 / 54B / 54D / 54EC / 54F / 54G / 54GA / 54GB)
// ==============================
var CGX_CAP_54 = 100000000;   // Rs 10 Cr cap for Sec 54 / 54F (w.e.f. 01.04.2024)
var CGX_CAP_54EC = 5000000;   // Rs 50 Lakh cap for Sec 54EC

function cgxOnAssetChange(){
  // Pre-fill net sale field requirement note
  var asset=document.getElementById('cgxAsset').value;
  var nsField=document.getElementById('cgxNetSale');
  if(asset==='other_ltca'){nsField.style.borderColor='#e84393';}
  else{nsField.style.borderColor='';}
}

function cgxPullFromCalc(){
  // Try to extract LTCG from cgResult innerText
  var r=document.getElementById('cgResult');
  if(!r||!r.innerText){alert('Please calculate the capital gain first using the calculator above.');return;}
  var txt=r.innerText;
  // Look for "Long Term Capital Gain" row
  var m=txt.match(/Long\s*Term\s*Capital\s*Gain[^0-9-]*([0-9,\-]+)/i);
  var ltcg=null;
  if(m){ltcg=parseFloat(m[1].replace(/,/g,''));}
  else{
    // Try to read "Capital Gain: Rs X"
    m=txt.match(/Capital\s*Gain[:\s]+Rs[\.\s]*([0-9,]+)/i);
    if(m)ltcg=parseFloat(m[1].replace(/,/g,''));
  }
  // Also try to pull net sale consideration
  var ns=null;
  var m2=txt.match(/Net\s*Sale\s*Consideration[^0-9-]*([0-9,]+)/i);
  if(m2)ns=parseFloat(m2[1].replace(/,/g,''));
  if(ltcg&&ltcg>0){
    document.getElementById('cgxLTCG').value=ltcg;
    if(ns)document.getElementById('cgxNetSale').value=ns;
    // Pull asset type and date heuristically
    var assetSel=document.getElementById('cgAsset').value;
    var ds=document.getElementById('cgDateSell').value;
    var map={'property':'res_house','listed_eq':'listed_eq','equity_mf':'listed_eq','unlisted':'other_ltca','gold':'other_ltca','debt_mf':'other_ltca','other':'other_ltca'};
    if(assetSel&&map[assetSel]){document.getElementById('cgxAsset').value=map[assetSel];cgxOnAssetChange();}
    if(ds)document.getElementById('cgxDate').value=ds;
  }else{
    alert('Could not detect a positive LTCG figure in the result. Please enter manually.');
  }
}

function _cgxAddYears(dateStr,years){
  if(!dateStr)return null;
  var d=new Date(dateStr);if(isNaN(d))return null;
  d.setFullYear(d.getFullYear()+years);
  return d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
}
function _cgxAddMonths(dateStr,months){
  if(!dateStr)return null;
  var d=new Date(dateStr);if(isNaN(d))return null;
  d.setMonth(d.getMonth()+months);
  return d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
}
function _cgxITRDueDate(ay){
  // Default non-audit due date 31 Jul of AY
  var startYr=parseInt(ay.split('-')[0],10);
  if(isNaN(startYr))return null;
  return '31 Jul '+startYr+' (non-audit) / 31 Oct '+startYr+' (audit)';
}

function checkCGExemption(){
  var asset=document.getElementById('cgxAsset').value;
  var ltcg=parseFloat(document.getElementById('cgxLTCG').value)||0;
  var netSale=parseFloat(document.getElementById('cgxNetSale').value)||0;
  var dateT=document.getElementById('cgxDate').value;
  var avail=parseFloat(document.getElementById('cgxAvail').value)||0;
  var intent=document.getElementById('cgxIntent').value;
  var ownsOther=document.getElementById('cgxOwnsOther').value==='yes';
  var status=document.getElementById('cgxStatus').value;
  var slab=parseFloat(document.getElementById('cgxSlab').value)||30;
  var ay=document.getElementById('cgxAY').value;
  var r=document.getElementById('cgExResult');

  if(!asset){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please select the type of asset sold</div>';return;}
  if(ltcg<=0){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please enter a positive Long-Term Capital Gain amount</div><div class="result-detail">Use the ↑ Pull button to fetch the figure from the calculator above, or enter it manually.</div>';return;}

  var indHuf=(status==='ind'||status==='huf');
  var sections=[];
  var notes=[];

  // Sec 54
  if(asset==='res_house' && indHuf){
    var newCost=avail;
    var raw=Math.min(ltcg,newCost);
    var ex=Math.min(raw,CGX_CAP_54);
    var capped=ex<raw;
    var cgas=Math.max(0,ltcg-newCost);
    if(ex<=0){cgas=ltcg;}
    sections.push({
      sec1961:'Sec 54',sec2025:'Sec 82',color:'#27ae60',
      title:'Reinvest in 1 Residential House (or up to 2 if LTCG ≤ Rs 2 Cr — once in lifetime)',
      exemption:Math.max(0,ex),capped:capped,
      cgas:cgas,
      details:[
        'Buy 1 yr before / 2 yrs after the date of transfer, OR construct within 3 yrs',
        'Property must be in India',
        'Cap of Rs 10 Crore on exemption (w.e.f. 01.04.2024)',
        'Unutilised amount must be deposited in CGAS before ITR due date u/s 139(1)'
      ],
      deadlinePurchase:_cgxAddYears(dateT,2),
      deadlineConstruct:_cgxAddYears(dateT,3),
      cgasBy:_cgxITRDueDate(ay)
    });
  }
  if(asset==='res_house' && !indHuf){
    notes.push('Sec 54 / 54F is restricted to Individuals & HUF — your filing status does not qualify for these reinvestment routes.');
  }

  // Sec 54F
  if(asset==='other_ltca' && indHuf){
    if(ownsOther){
      sections.push({
        sec1961:'Sec 54F',sec2025:'Sec 87',color:'#d63031',
        title:'Reinvest in 1 Residential House — NOT ELIGIBLE',
        exemption:0,capped:false,cgas:0,
        details:['You own more than 1 residential house on the date of transfer (other than the new one) — Sec 54F is denied entirely.','Consider Sec 54EC bonds as an alternative.']
      });
    }else{
      if(netSale<=0){
        notes.push('For Sec 54F you must enter the Net Sale Consideration (sale price minus transfer expenses) — exemption is proportionate.');
      }
      var newCostF=avail;
      var ratio=netSale>0?(newCostF/netSale):0;
      var rawF=ltcg*Math.min(1,ratio);
      var exF=Math.min(rawF,CGX_CAP_54);
      var cappedF=exF<rawF;
      var cgasF=Math.max(0,netSale-newCostF);
      sections.push({
        sec1961:'Sec 54F',sec2025:'Sec 87',color:'#27ae60',
        title:'Reinvest entire Net Sale Consideration in 1 Residential House',
        exemption:Math.max(0,exF),capped:cappedF,cgas:cgasF,
        details:[
          'Exemption = LTCG × (Cost of New House ÷ Net Sale Consideration)',
          'For full exemption you must invest the entire net consideration (not just the gain)',
          'Time limits same as Sec 54 — 1 yr before / 2 yrs after for purchase, 3 yrs for construction',
          'Must NOT own > 1 other residential house on the date of transfer',
          'Must NOT purchase another house within 2 yrs / construct within 3 yrs of this transfer (otherwise exemption withdrawn)',
          'Cap of Rs 10 Crore on exemption (w.e.f. 01.04.2024)'
        ],
        deadlinePurchase:_cgxAddYears(dateT,2),
        deadlineConstruct:_cgxAddYears(dateT,3),
        cgasBy:_cgxITRDueDate(ay)
      });
    }
  }

  // Sec 54EC bonds (LTCG on land/building only)
  if(asset==='res_house' || asset==='land_building' || asset==='other_ltca'){
    // 54EC strictly for land/building — but residential house qualifies (it's a building)
    // For "other_ltca" it may or may not be — show with caveat
    var bondAvail=Math.min(avail,CGX_CAP_54EC);
    var rawEC=Math.min(ltcg,CGX_CAP_54EC);
    var exEC=bondAvail>0?Math.min(bondAvail,ltcg):rawEC;
    var capNote=ltcg>CGX_CAP_54EC?'Capped at Rs 50 Lakh per FY':'Within the Rs 50 Lakh cap';
    sections.push({
      sec1961:'Sec 54EC',sec2025:'Sec 85',color:asset==='other_ltca'?'#f39c12':'#27ae60',
      title:'Invest in NHAI / REC / PFC / IRFC Bonds (5-year lock-in)',
      exemption:Math.max(0,exEC),capped:exEC<rawEC&&bondAvail<rawEC,cgas:0,
      details:[
        'Eligible bonds: NHAI 54EC, REC 54EC, PFC 54EC, IRFC 54EC (any of these)',
        'Investment must be made within 6 months from the date of transfer',
        '5-year lock-in — cannot be sold, transferred, or used as security for any loan',
        'Maximum Rs 50 Lakh per financial year — and Rs 50 Lakh combined across the 2 FYs of the same transfer (w.e.f. AY 2019-20)',
        'No CGAS — bonds must be physically purchased within 6 months (the deadline is hard, not extendable)',
        capNote+(asset==='other_ltca'?' | NOTE: Sec 54EC strictly applies to long-term land or building — verify your asset qualifies':'')
      ],
      deadlineBonds:_cgxAddMonths(dateT,6)
    });
  }

  // Sec 54B (agricultural land)
  if(asset==='agri_land' && indHuf){
    var newAgri=avail;
    var rawB=Math.min(ltcg,newAgri);
    var cgasB=Math.max(0,ltcg-newAgri);
    sections.push({
      sec1961:'Sec 54B',sec2025:'Sec 83',color:'#27ae60',
      title:'Reinvest in Other Agricultural Land',
      exemption:Math.max(0,rawB),capped:false,cgas:cgasB,
      details:[
        'Land sold must have been used for agricultural purposes by self / parent / HUF for 2 yrs immediately preceding transfer',
        'Reinvest in another agricultural land (urban or rural) within 2 yrs from transfer',
        'New land must NOT be transferred within 3 yrs (otherwise exemption withdrawn)',
        'Unutilised amount → CGAS before ITR due date'
      ],
      deadlinePurchase:_cgxAddYears(dateT,2),
      cgasBy:_cgxITRDueDate(ay)
    });
  }

  // Sec 54D (compulsory acquisition of industrial L/B)
  if(asset==='industrial_lb'){
    var newInd=avail;
    var rawD=Math.min(ltcg,newInd);
    var cgasD=Math.max(0,ltcg-newInd);
    sections.push({
      sec1961:'Sec 54D',sec2025:'Sec 84',color:'#27ae60',
      title:'Reinvest in Land/Building for Industrial Undertaking',
      exemption:Math.max(0,rawD),capped:false,cgas:cgasD,
      details:[
        'Applies only to compulsory acquisition under any law',
        'Original land/building must have been used for the industrial undertaking for 2 yrs immediately preceding transfer',
        'Reinvest within 3 yrs from receipt of compensation',
        'New asset must NOT be transferred within 3 yrs (otherwise exemption withdrawn)',
        'Unutilised amount → CGAS before ITR due date'
      ],
      deadlinePurchase:_cgxAddYears(dateT,3),
      cgasBy:_cgxITRDueDate(ay)
    });
  }

  // Sec 54G/54GA — info only (industrial shifting)
  if(intent==='industrial'||asset==='industrial_lb'){
    notes.push('Sec 54G / 54GA — Shifting of industrial undertaking from urban to rural area / SEZ: reinvest in new land, building, plant & machinery and shifting expenses, within 1 year before / 3 years after the transfer. Unutilised amount → CGAS. Open to all assessees.');
  }

  // Sec 54GB (eligible startup)
  if(asset==='res_house' && indHuf && (intent==='startup'||intent==='any')){
    notes.push('Sec 54GB — LTCG on a residential house can be exempt if you subscribe ≥ 50% equity in an eligible SME / start-up company that uses the proceeds to purchase new plant & machinery. Sunset clause for eligible startups extended to 31.03.2025 by Finance Act 2024 — verify current applicability before claiming.');
  }

  // Filter by intent if specified
  var filtered=sections;
  if(intent==='house')filtered=sections.filter(function(s){return s.sec1961==='Sec 54'||s.sec1961==='Sec 54F';});
  else if(intent==='bonds')filtered=sections.filter(function(s){return s.sec1961==='Sec 54EC';});
  else if(intent==='agri')filtered=sections.filter(function(s){return s.sec1961==='Sec 54B';});
  else if(intent==='industrial')filtered=sections.filter(function(s){return s.sec1961==='Sec 54D';});
  if(filtered.length===0)filtered=sections;

  // Pick best (highest exemption) — but Sec 54EC can stack with house route up to its cap if from same gain? Practically, the same gain can't be exempted twice — so we show alternatives.
  var best=null;
  filtered.forEach(function(s){if(!best||s.exemption>best.exemption)best=s;});
  var bestExemption=best?best.exemption:0;
  var taxableGain=Math.max(0,ltcg-bestExemption);
  // LTCG tax @ 12.5% (post 23.07.2024) — for property route. We'll show 12.5%.
  var taxBefore=Math.round(ltcg*0.125);
  var taxAfter=Math.round(taxableGain*0.125);
  var saved=taxBefore-taxAfter;

  // Render
  var cls=bestExemption>0?'result-box presumptive':'result-box not-applicable';
  r.className=cls;
  var html='<div class="result-title" style="color:#e84393;">🛡️ Capital Gains Exemption Plan</div>';
  html+='<div class="result-detail">';
  html+='<p style="margin:6px 0 12px;"><strong>Long-Term Capital Gain:</strong> Rs '+fmt(ltcg)+(dateT?' &nbsp;|&nbsp; <strong>Date of Transfer:</strong> '+new Date(dateT).toLocaleDateString('en-IN'):'')+'</p>';

  if(filtered.length===0||(filtered.length===1&&filtered[0].exemption===0)){
    html+='<p style="color:#d63031;font-weight:600;">No reinvestment-based exemption appears to be available for the inputs provided. The full LTCG of Rs '+fmt(ltcg)+' will be taxable.</p>';
  }else{
    html+='<div class="table-scroll"><table class="limits-table" style="margin-top:6px;font-size:0.86rem;">';
    html+='<thead><tr style="background:#fde7f1;"><th>Section (1961)</th><th>Section (2025)</th><th>Reinvestment Route</th><th>Eligible Exemption</th><th>CGAS Deposit Needed</th></tr></thead><tbody>';
    filtered.forEach(function(s){
      html+='<tr><td><strong>'+s.sec1961+'</strong></td><td><strong>'+s.sec2025+'</strong></td><td>'+s.title+'</td><td style="color:'+s.color+';font-weight:600;">Rs '+fmt(s.exemption)+(s.capped?' <span style="font-size:0.72rem;color:#e67e22;">(capped)</span>':'')+'</td><td>'+(s.cgas>0?'Rs '+fmt(s.cgas):'—')+'</td></tr>';
    });
    html+='</tbody></table></div>';

    if(best){
      html+='<div style="background:#e8f8f5;border:2px solid #00b894;border-radius:8px;padding:14px;margin-top:14px;">';
      html+='<h4 style="margin:0 0 8px;color:#00b894;">✅ Recommended: '+best.sec1961+' / '+best.sec2025+'</h4>';
      html+='<p style="margin:4px 0;"><strong>Exemption Available:</strong> Rs '+fmt(best.exemption)+(best.capped?' <span style="color:#e67e22;">(capped at Rs 10 Cr)</span>':'')+'</p>';
      if(best.cgas>0)html+='<p style="margin:4px 0;color:#d63031;"><strong>CGAS Deposit Required:</strong> Rs '+fmt(best.cgas)+' — must be deposited <strong>before '+(best.cgasBy||'ITR due date u/s 139(1)')+'</strong></p>';
      html+='<p style="margin:4px 0;"><strong>Action plan:</strong></p><ul style="margin:4px 0 4px 18px;font-size:0.86rem;line-height:1.65;">';
      best.details.forEach(function(d){html+='<li>'+d+'</li>';});
      if(best.deadlinePurchase)html+='<li><strong>Purchase deadline:</strong> '+best.deadlinePurchase+'</li>';
      if(best.deadlineConstruct)html+='<li><strong>Construction deadline:</strong> '+best.deadlineConstruct+'</li>';
      if(best.deadlineBonds)html+='<li><strong>Bond purchase deadline:</strong> '+best.deadlineBonds+' (hard 6-month window)</li>';
      html+='</ul></div>';
    }

    html+='<div style="background:#fef9e7;border-left:4px solid #f39c12;padding:10px 14px;margin-top:12px;border-radius:6px;">';
    html+='<p style="margin:0;font-size:0.86rem;"><strong>💰 Tax Saving Summary (LTCG @ 12.5%):</strong></p>';
    html+='<table class="limits-table" style="margin-top:6px;font-size:0.84rem;"><tbody>';
    html+='<tr><td>Tax payable WITHOUT exemption</td><td><strong>Rs '+fmt(taxBefore)+'</strong></td></tr>';
    html+='<tr><td>Best available exemption</td><td>(-) Rs '+fmt(bestExemption)+'</td></tr>';
    html+='<tr><td>Taxable LTCG after exemption</td><td>Rs '+fmt(taxableGain)+'</td></tr>';
    html+='<tr><td>Tax payable WITH exemption</td><td><strong>Rs '+fmt(taxAfter)+'</strong></td></tr>';
    html+='<tr style="background:#e8f8f5;"><td><strong>Tax Saved</strong></td><td style="color:#00b894;"><strong>Rs '+fmt(saved)+'</strong></td></tr>';
    html+='</tbody></table>';
    html+='<p style="margin:6px 0 0;font-size:0.74rem;color:#777;">Plus 4% Health & Education Cess (and surcharge if applicable). For property acquired before 23.07.2024 you may also choose the 20% with-indexation route under the grandfathering option — compute both before deciding.</p>';
    html+='</div>';
  }

  if(notes.length){
    html+='<div style="margin-top:12px;padding:10px 14px;background:#fef0f5;border-left:4px solid #fd79a8;border-radius:6px;">';
    html+='<p style="margin:0 0 4px;font-weight:600;color:#a83b6d;font-size:0.86rem;">📌 Additional Notes</p>';
    html+='<ul style="margin:4px 0 4px 18px;font-size:0.82rem;color:#555;line-height:1.6;">';
    notes.forEach(function(n){html+='<li>'+n+'</li>';});
    html+='</ul></div>';
  }

  html+='<p style="margin-top:12px;font-size:0.74rem;color:#999;">⚠ This planner gives an indicative figure based on your inputs. The exact exemption depends on the actual reinvestment, asset characterisation, and the cost / sale figures verified from documents. Always confirm with a Chartered Accountant before claiming the exemption in your return.</p>';

  html+='</div>';
  r.innerHTML=html;
}

function resetCGExemption(){
  ['cgxLTCG','cgxNetSale','cgxDate','cgxAvail','cgxSlab'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=(id==='cgxSlab'?'30':'');});
  document.getElementById('cgxAsset').value='';
  document.getElementById('cgxIntent').value='any';
  document.getElementById('cgxOwnsOther').value='no';
  document.getElementById('cgxStatus').value='ind';
  document.getElementById('cgxAY').value='2027-28';
  var r=document.getElementById('cgExResult');r.className='result-box';r.innerHTML='';
}


// ==============================
// INTEREST & PENALTY CALCULATOR (234A/B/C/F)
// ==============================
function calcInterest(){
var taxLiab=parseFloat(document.getElementById('ipTaxLiab').value)||0;
var adv1=parseFloat(document.getElementById('ipAdv1').value)||0;
var adv2=parseFloat(document.getElementById('ipAdv2').value)||0;
var adv3=parseFloat(document.getElementById('ipAdv3').value)||0;
var adv4=parseFloat(document.getElementById('ipAdv4').value)||0;
var tds=parseFloat(document.getElementById('ipTDS').value)||0;
var sat=parseFloat(document.getElementById('ipSAT').value)||0;
var income=parseFloat(document.getElementById('ipIncome').value)||0;
var ay=document.getElementById('ipAY').value;
var dueSel=document.getElementById('ipDueDate').value;
var fileDate=document.getElementById('ipFileDate').value;
var r=document.getElementById('ipResult');
if(!taxLiab){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please enter tax liability</div>';return;}
var totalAdvance=adv1+adv2+adv3+adv4;
var totalPaid=totalAdvance+tds+sat;
var assessedTax=taxLiab-tds; // Tax payable after TDS = assessed tax for 234B
var advanceTaxPaid=totalAdvance;
// Due dates
var ayStart=parseInt(ay.split('-')[0]);
var dueMap={jul31:new Date(ayStart,6,31),oct31:new Date(ayStart,9,31),nov30:new Date(ayStart,10,30)};
var dueDate=dueMap[dueSel];
var actualDate=fileDate?new Date(fileDate):null;

// === 234C — Deferment of advance tax ===
var int234C=0;
if(assessedTax>=10000){
var req1=Math.round(taxLiab*0.15),req2=Math.round(taxLiab*0.45),req3=Math.round(taxLiab*0.75),req4=taxLiab;
var cum1=adv1,cum2=adv1+adv2,cum3=adv1+adv2+adv3,cum4=totalAdvance;
// Q1: shortfall if paid < 15% → 1% * 3 months
if(cum1<req1)int234C+=Math.round((req1-cum1)*0.01*3);
// Q2: shortfall if cumulative < 45% → 1% * 3 months
if(cum2<req2)int234C+=Math.round((req2-cum2)*0.01*3);
// Q3: shortfall if cumulative < 75% → 1% * 3 months
if(cum3<req3)int234C+=Math.round((req3-cum3)*0.01*3);
// Q4: shortfall if cumulative < 100% → 1% * 1 month
if(cum4<req4)int234C+=Math.round((req4-cum4)*0.01*1);
}

// === 234B — Short advance tax ===
var int234B=0;
if(assessedTax>=10000&&advanceTaxPaid<(assessedTax*0.9)){
var shortfall=assessedTax-advanceTaxPaid;
// From 1 Apr of AY to date of filing/assessment
var startB=new Date(ayStart,3,1); // 1 Apr of AY
var endB=actualDate||new Date(ayStart,3,1);
if(endB<startB)endB=startB;
var monthsB=Math.ceil((endB-startB)/(1000*60*60*24*30))||1;
if(monthsB<1)monthsB=1;
int234B=Math.round(shortfall*0.01*monthsB);
}

// === 234A — Late filing ===
var int234A=0;
if(actualDate&&dueDate&&actualDate>dueDate){
var unpaidAtDue=Math.max(taxLiab-totalPaid+sat,0); // tax outstanding at due date (before SAT)
var monthsA=Math.ceil((actualDate-dueDate)/(1000*60*60*24*30))||1;
if(monthsA<1)monthsA=1;
int234A=Math.round(unpaidAtDue*0.01*monthsA);
}

// === 234F — Late filing fee ===
var fee234F=0;
if(actualDate&&dueDate&&actualDate>dueDate){
fee234F=income<=500000?1000:5000;
}

var totalInt=int234A+int234B+int234C+fee234F;
r.className='result-box not-applicable';
r.innerHTML='<div class="result-title">Total Interest & Penalty: Rs '+fmt(totalInt)+'</div><div class="result-detail"><table class="limits-table" style="margin-top:10px;"><tr><th>Section</th><th>Nature</th><th>Amount</th></tr><tr><td><strong>234C</strong></td><td>Deferment of Advance Tax Installments</td><td><strong>Rs '+fmt(int234C)+'</strong></td></tr><tr><td><strong>234B</strong></td><td>Short Payment of Advance Tax</td><td><strong>Rs '+fmt(int234B)+'</strong></td></tr><tr><td><strong>234A</strong></td><td>Late Filing of Return</td><td><strong>Rs '+fmt(int234A)+'</strong></td></tr><tr><td><strong>234F</strong></td><td>Late Filing Fee</td><td><strong>Rs '+fmt(fee234F)+'</strong></td></tr><tr style="background:#fde8e8;"><td colspan="2"><strong>TOTAL</strong></td><td><strong>Rs '+fmt(totalInt)+'</strong></td></tr></table><div style="margin-top:12px;font-size:0.85rem;"><strong>Summary:</strong><br>Tax Liability: Rs '+fmt(taxLiab)+' | TDS/TCS: Rs '+fmt(tds)+' | Advance Tax: Rs '+fmt(totalAdvance)+' | SAT: Rs '+fmt(sat)+'<br>Assessed Tax (after TDS): Rs '+fmt(assessedTax)+(actualDate&&dueDate?'<br>Due Date: '+dueDate.toLocaleDateString('en-IN')+' | Filed: '+actualDate.toLocaleDateString('en-IN'):'')+'</div></div>';
}
function resetIP(){['ipTaxLiab','ipAdv1','ipAdv2','ipAdv3','ipAdv4','ipTDS','ipSAT','ipIncome'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('ipFileDate').value='';document.getElementById('ipResult').className='result-box';document.getElementById('ipResult').innerHTML='';}


// ==============================
// IMPACT ANALYZER — IT Act 1961 vs 2025
// ==============================
function analyzeImpact(){
var entity=document.getElementById('imEntity').value;
var turnover=parseFloat(document.getElementById('imTurnover').value)||0;
var audit=document.getElementById('imAudit').value==='yes';
var capGain=document.getElementById('imCapGain').value==='yes';
var tp=document.getElementById('imTP').value==='yes';
var via=document.getElementById('imVIA').value==='yes';
var hasTDS=document.getElementById('imTDS').value==='yes';
var partner=document.getElementById('imPartner').value==='yes';
var r=document.getElementById('imResult');
var changes=[];
// Universal changes
changes.push({area:'Terminology',old:'Previous Year (PY) + Assessment Year (AY)',new_:'<strong>Tax Year</strong> — single unified concept. FY 2026-27 = Tax Year 2026-27.',impact:'high',action:'Update all documents, letters, and internal references. No more AY/PY distinction.'});
changes.push({area:'Return Filing',old:'Sec 139 — ITR-1 to ITR-7',new_:'<strong>Sec 263</strong> — Return of Income. New form numbers expected.',impact:'medium',action:'Await CBDT notification for new ITR form numbers under Rules 2026.'});
changes.push({area:'Default Tax Regime',old:'Old Regime default; 115BAC opt-in for New Regime',new_:'<strong>New Regime is DEFAULT</strong>. Old regime available only on opt-in.',impact:'high',action:'If client benefits from old regime deductions, ensure Form 10-IE equivalent is filed to opt in.'});
// Entity-specific
if(audit){
changes.push({area:'Tax Audit',old:'Form 3CA/3CB + 3CD (Sec 44AB)',new_:'<strong>Form No. 26</strong> under <strong>Sec 63</strong> (Rule 47, IT Rules 2026). Consolidated form with 53 clauses. <span style="color:#d63031;">(Note: Form No. 26 is the anticipated consolidated tax audit form — actual CBDT notification prescribing the form is awaited as on April 2026.)</span>',impact:'high',action:'Prepare for Form 26 structure — Yes/No trigger-based schedules, expanded IT systems audit, GST linkage reporting.'});
}
if(capGain){
changes.push({area:'Capital Gains',old:'Sec 45-55A, multiple rates, indexation available',new_:'<strong>Chapter VIII (Sec 67-91)</strong>. Uniform LTCG: 12.5%. STCG listed: 20%. No indexation (except grandfathered property).',impact:'high',action:'Review all LTCG computations. Indexation benefit no longer available for new acquisitions. Property bought before 23.07.2024 has grandfathering option.'});
}
if(via){
changes.push({area:'Chapter VI-A Deductions',old:'Sec 80C to 80U — up to Rs 1.5L (80C), 80D, 80G etc.',new_:'<strong>Chapter VIII (Sec 123-154)</strong>. Renumbered but most deductions retained with same limits under old regime.',impact:'medium',action:'Map each claimed deduction to new section number. Deductions only available if client opts for old regime. New regime: only Std Deduction (Rs 75,000) + NPS (employer contribution).'});
}
if(hasTDS){
changes.push({area:'TDS/TCS Sections',old:'Sec 192-206C (30+ sections)',new_:'<strong>Sec 393-421</strong>. Sections renumbered and some consolidated. New Sec 194T (firm→partner) now mapped.',impact:'high',action:'Update TDS software section mapping. Verify all TDS rates under new section numbers. Quarterly return forms will change.'});
}
if(partner){
changes.push({area:'Partnership Taxation',old:'Sec 40(b) — salary/interest limits',new_:'New provisions under Sec 63. <strong>TDS on partner remuneration (194T equivalent)</strong> now embedded in new Act.',impact:'medium',action:'Ensure TDS deducted on partner salary/interest/bonus/commission exceeding Rs 20,000 p.a.'});
}
if(tp){
changes.push({area:'Transfer Pricing',old:'Sec 92-92F, 3CEB report',new_:'Dedicated chapter. Enhanced documentation and reporting requirements.',impact:'medium',action:'Review TP documentation requirements under new Act provisions.'});
}
if(entity==='company'){
changes.push({area:'Company Tax Rate',old:'Sec 115BAA (22%), 115BAB (15%)',new_:'Concessional rates continued under new Act with equivalent provisions.',impact:'low',action:'Verify applicable tax rate option under new section numbers.'});
}
if(entity==='trust'){
changes.push({area:'Trust Taxation',old:'Sec 11-13, Form 10B/10BB',new_:'Dedicated chapter for exempt entities. Enhanced compliance and audit trail requirements.',impact:'medium',action:'Review registration validity and new compliance forms.'});
}
// Interest sections
changes.push({area:'Interest on Defaults',old:'234A, 234B, 234C (1% p.m.)',new_:'<strong>Sec 423, 424, 425</strong>. Same rates (1% p.m.). Calculation method unchanged.',impact:'low',action:'No change in computation — only section numbers change.'});
changes.push({area:'Penalties',old:'Sec 270A (under-reporting), 271 series',new_:'<strong>Sec 434-441</strong>. Rationalized penalty provisions with clearer classification.',impact:'medium',action:'Review penalty exposure under new provisions. Mis-reporting vs under-reporting distinction continues.'});

var html='<div class="result-title">Impact Analysis — '+entity.charAt(0).toUpperCase()+entity.slice(1)+(turnover?' (Turnover: Rs '+turnover+' Cr)':'')+'</div><div class="result-detail">';
html+='<p style="margin-bottom:12px;"><strong>'+changes.length+' areas impacted</strong> based on your client profile. New Act effective from 01.04.2026 (Tax Year 2026-27).</p>';
html+='<table class="limits-table"><thead><tr><th style="width:120px;">Area</th><th>Old Act (1961)</th><th>New Act (2025)</th><th style="width:80px;">Impact</th></tr></thead><tbody>';
changes.forEach(function(c){
var tag=c.impact==='high'?'<span class="tag tag-high">High</span>':c.impact==='medium'?'<span class="tag tag-medium">Medium</span>':'<span class="tag tag-low">Low</span>';
html+='<tr><td><strong>'+c.area+'</strong></td><td style="font-size:0.83rem;">'+c.old+'</td><td style="font-size:0.83rem;">'+c.new_+'</td><td>'+tag+'</td></tr>';
html+='<tr style="background:#f8f9fa;"><td colspan="4" style="font-size:0.82rem;color:#636e72;padding:6px 12px;"><strong>Action:</strong> '+c.action+'</td></tr>';
});
html+='</tbody></table></div>';
r.className='result-box presumptive';
r.innerHTML=html;
}

// ==============================
// SMART SEARCH (Cross-reference)

// ==================== IT REFUND & 244A JS ====================
function calcRefund(){
var tds=parseFloat(document.getElementById('rfTDS').value)||0;
var advTax=parseFloat(document.getElementById('rfAdvTax').value)||0;
var sat=parseFloat(document.getElementById('rfSAT').value)||0;
var taxDue=parseFloat(document.getElementById('rfTaxDue').value)||0;
var timely=document.getElementById('rfTimely').value;
var dueType=document.getElementById('rfDueType').value;
var fileDateStr=document.getElementById('rfFileDate').value;
var refundDateStr=document.getElementById('rfRefundDate').value;
var ay=document.getElementById('rfAY').value;
var r=document.getElementById('rfResult');
var totalPaid=tds+advTax+sat;
if(totalPaid<=0&&taxDue<=0){r.className='result-box applicable';r.innerHTML='<div class="result-title">Please enter tax details.</div>';return;}
var refundAmt=totalPaid-taxDue;
if(refundAmt<=0){r.className='result-box applicable';r.innerHTML='<div class="result-title" style="color:#d63031;">No Refund Due</div><div class="result-detail">Total tax paid (Rs '+fmt(totalPaid)+') is less than or equal to tax determined (Rs '+fmt(taxDue)+'). You owe Rs '+fmt(Math.abs(refundAmt))+' to the department.</div>';return;}
var refundTDSAdv=Math.max(0,tds+advTax-taxDue);
var refundSAT=Math.max(0,refundAmt-refundTDSAdv);
var ayYear=parseInt(ay.split('-')[0]);
var aprStart=new Date(ayYear,3,1);
var dueDate;
if(dueType==='july')dueDate=new Date(ayYear,6,31);
else if(dueType==='october')dueDate=new Date(ayYear,9,31);
else dueDate=new Date(ayYear,10,30);
var fileDate=fileDateStr?new Date(fileDateStr):new Date();
var refundDate=refundDateStr?new Date(refundDateStr):new Date();
var interestStart;
if(timely==='yes'){interestStart=aprStart;}else{interestStart=fileDate;}
var diffMs=refundDate.getTime()-interestStart.getTime();
var months=Math.ceil(diffMs/(1000*60*60*24*30.44));
if(months<0)months=0;
var noInterest=(refundAmt<100)||(refundAmt<=(taxDue*0.1));
var interest244A=0;
if(!noInterest&&refundTDSAdv>0){interest244A=Math.round(refundTDSAdv*0.005*months);}
var satInterest=0;
r.className='result-box presumptive';
var html='<div class="result-title">Refund & Section 244A Interest Computation</div><div class="result-detail">';
html+='<h3 style="margin:10px 0 6px;color:var(--accent);">Step A — Refund Amount</h3>';
html+='<table class="limits-table"><tr><td>TDS</td><td>Rs '+fmt(tds)+'</td></tr>';
html+='<tr><td>Advance Tax</td><td>Rs '+fmt(advTax)+'</td></tr>';
html+='<tr><td>Self Assessment Tax</td><td>Rs '+fmt(sat)+'</td></tr>';
html+='<tr><td><strong>Total Tax Paid</strong></td><td><strong>Rs '+fmt(totalPaid)+'</strong></td></tr>';
html+='<tr><td>Tax Determined on Assessment</td><td>Rs '+fmt(taxDue)+'</td></tr>';
html+='<tr style="background:#e8f8f5;"><td><strong>Refund Due</strong></td><td><strong>Rs '+fmt(refundAmt)+'</strong></td></tr>';
if(noInterest){html+='<tr style="background:#fef9e7;"><td colspan="2"><strong>No interest u/s 244A payable</strong> — Refund '+(refundAmt<100?'is less than Rs 100':'is ≤ 10% of tax determined')+'</td></tr>';}
html+='</table>';
if(!noInterest){
html+='<h3 style="margin:14px 0 6px;color:var(--accent);">Step B — Section 244A Interest</h3>';
html+='<table class="limits-table"><tr><td>Refund out of TDS + Advance Tax</td><td>Rs '+fmt(refundTDSAdv)+'</td></tr>';
html+='<tr><td>Interest period</td><td>'+interestStart.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})+' to '+refundDate.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})+'</td></tr>';
html+='<tr><td>Months</td><td>'+months+'</td></tr>';
html+='<tr style="background:#e8f8f5;"><td><strong>Interest @ 6% p.a. (0.5%/month)</strong></td><td><strong>Rs '+fmt(interest244A)+'</strong></td></tr></table>';
}
html+='<h3 style="margin:14px 0 6px;color:var(--accent);">Total</h3>';
html+='<table class="limits-table"><tr style="background:#dfe6e9;font-weight:700;font-size:1.05rem;"><td>Total Refund + Interest</td><td>Rs '+fmt(refundAmt+interest244A)+'</td></tr></table>';
html+='<p style="margin-top:10px;font-size:0.82rem;color:#666;">Interest u/s 244A is taxable as Income from Other Sources in the year of receipt.</p></div>';
r.innerHTML=html;
}
function resetRefund(){['rfTDS','rfAdvTax','rfSAT','rfTaxDue','rfFileDate','rfRefundDate'].forEach(function(id){document.getElementById(id).value='';});document.getElementById('rfTimely').value='yes';document.getElementById('rfResult').className='result-box';document.getElementById('rfResult').innerHTML='';}


