// js/gst.js — extracted from index.html
// Generated by split.cjs

// ==============================
// TAB 5: GST RATES
// ==============================
var gstItems=[
// === EXEMPT (0%) — Notf 02/2017-CT(Rate) as amended by 10/2025-CT(Rate) ===
{item:"Fresh Milk",hsn:"0401",rate:"0%",cat:"Exempt"},{item:"Curd / Lassi / Buttermilk (unbranded)",hsn:"0403",rate:"0%",cat:"Exempt"},{item:"Fresh Fruits",hsn:"0803-0810",rate:"0%",cat:"Exempt"},{item:"Fresh Vegetables",hsn:"0701-0714",rate:"0%",cat:"Exempt"},{item:"Bread (unbranded)",hsn:"1905",rate:"0%",cat:"Exempt"},{item:"Salt",hsn:"2501",rate:"0%",cat:"Exempt"},{item:"Rice (unbranded loose)",hsn:"1006",rate:"0%",cat:"Exempt"},{item:"Wheat / Meslin (unbranded loose)",hsn:"1001",rate:"0%",cat:"Exempt"},{item:"Pulses / Dal (unbranded loose)",hsn:"0713",rate:"0%",cat:"Exempt"},{item:"Cereals (unbranded)",hsn:"1001-1008",rate:"0%",cat:"Exempt"},{item:"Jaggery / Gur",hsn:"1701",rate:"0%",cat:"Exempt"},{item:"Fresh Meat / Fish",hsn:"0201-0307",rate:"0%",cat:"Exempt"},{item:"Eggs",hsn:"0407",rate:"0%",cat:"Exempt"},{item:"Honey (natural)",hsn:"0409",rate:"0%",cat:"Exempt"},{item:"Live Animals",hsn:"0101-0106",rate:"0%",cat:"Exempt"},{item:"Bangles (non-precious)",hsn:"7117",rate:"0%",cat:"Exempt"},{item:"Kumkum / Bindi / Sindoor",hsn:"3304",rate:"0%",cat:"Exempt"},{item:"Stamp Papers / Court Stamps",hsn:"4907",rate:"0%",cat:"Exempt"},{item:"Education Services",hsn:"9992",rate:"0%",cat:"Exempt"},{item:"Healthcare Services",hsn:"9993",rate:"0%",cat:"Exempt"},{item:"Agricultural Services",hsn:"9986",rate:"0%",cat:"Exempt"},{item:"Public Transport (non-AC bus)",hsn:"9964",rate:"0%",cat:"Exempt"},{item:"Blood / Blood Products",hsn:"3002",rate:"0%",cat:"Exempt"},{item:"Contraceptives",hsn:"4014",rate:"0%",cat:"Exempt"},{item:"Sanitary Napkins",hsn:"9619",rate:"0%",cat:"Exempt"},
{item:"Term Life Insurance — Individual (Exempt post 56th Council)",hsn:"9971",rate:"0%",cat:"Exempt"},{item:"Health Insurance — Senior Citizens (Exempt post 56th Council)",hsn:"9971",rate:"0%",cat:"Exempt"},{item:"Health Insurance — up to Rs 5L cover (Exempt post 56th Council)",hsn:"9971",rate:"0%",cat:"Exempt"},
// === SPECIAL RATES — Gold, Diamonds, Real Estate ===
{item:"Gold / Silver Jewelry",hsn:"7113",rate:"3%",cat:"Special"},{item:"Gold Bars / Biscuits",hsn:"7108",rate:"3%",cat:"Special"},{item:"Silver Articles",hsn:"7114",rate:"3%",cat:"Special"},{item:"Rough Diamonds (uncut)",hsn:"7102",rate:"0.25%",cat:"Special"},{item:"Cut & Polished Diamonds",hsn:"7102",rate:"1.5%",cat:"Special"},{item:"Diamond Jewelry",hsn:"7113",rate:"3%",cat:"Special"},{item:"Affordable Housing (≤₹45L, ≤60/90 sqm)",hsn:"9954",rate:"1%",cat:"Special"},{item:"Non-affordable Housing (under construction)",hsn:"9954",rate:"5%",cat:"Special"},{item:"Commercial Property (under construction)",hsn:"9954",rate:"18%",cat:"Special"},
// === 5% — Notf 01/2017-CT(Rate) Sch I as amended by 09/2025-CT(Rate) ===
{item:"Sugar",hsn:"1701",rate:"5%",cat:"5%"},{item:"Tea",hsn:"0902",rate:"5%",cat:"5%"},{item:"Coffee (not instant)",hsn:"0901",rate:"5%",cat:"5%"},{item:"Coal / Lignite",hsn:"2701",rate:"5%",cat:"5%"},{item:"LPG for household",hsn:"2711",rate:"5%",cat:"5%"},{item:"Kerosene (PDS)",hsn:"2710",rate:"5%",cat:"5%"},{item:"Fertilizers",hsn:"3102-3105",rate:"5%",cat:"5%"},{item:"Newspaper / Periodicals",hsn:"4902",rate:"5%",cat:"5%"},{item:"Branded Packaged Cereals",hsn:"1001-1008",rate:"5%",cat:"5%"},{item:"Branded Namkeen / Snacks",hsn:"2106",rate:"5%",cat:"5%"},{item:"Spices (packed branded)",hsn:"0904-0910",rate:"5%",cat:"5%"},{item:"Edible Oil (packed branded)",hsn:"1507-1518",rate:"5%",cat:"5%"},{item:"Skimmed Milk Powder",hsn:"0402",rate:"5%",cat:"5%"},{item:"Fabric (cotton, silk, wool)",hsn:"5007-5212",rate:"5%",cat:"5%"},{item:"Footwear (≤ ₹2,500)",hsn:"6401-6405",rate:"5%",cat:"5%"},{item:"Apparel (≤ ₹2,500)",hsn:"6101-6117",rate:"5%",cat:"5%"},{item:"Handloom Products",hsn:"5801-5811",rate:"5%",cat:"5%"},{item:"Life-saving Drugs",hsn:"3003-3004",rate:"5%",cat:"5%"},
{item:"Soap / Detergent (moved from 18%)",hsn:"3401",rate:"5%",cat:"5%"},{item:"Toothpaste (moved from 18%)",hsn:"3306",rate:"5%",cat:"5%"},{item:"Shampoo / Hair Oil (moved from 18%)",hsn:"3305",rate:"5%",cat:"5%"},{item:"Talcum Powder / Face Powder",hsn:"3304",rate:"5%",cat:"5%"},{item:"Shaving Cream / Razor",hsn:"3307/8212",rate:"5%",cat:"5%"},
{item:"Butter / Ghee (moved from 12%)",hsn:"0405",rate:"5%",cat:"5%"},{item:"Cheese / Paneer (branded)",hsn:"0406",rate:"5%",cat:"5%"},{item:"Dry Fruits (packed)",hsn:"0801-0802",rate:"5%",cat:"5%"},{item:"Fruit Juices (packed)",hsn:"2009",rate:"5%",cat:"5%"},{item:"Medicines / Pharma (general)",hsn:"3003-3004",rate:"5%",cat:"5%"},{item:"Processed Food (frozen/canned)",hsn:"1601-1605",rate:"5%",cat:"5%"},{item:"Diagnostic Kits / Reagents",hsn:"3822",rate:"5%",cat:"5%"},
{item:"Economy Air Tickets",hsn:"9964",rate:"5%",cat:"5%"},{item:"Rail Tickets (sleeper)",hsn:"9964",rate:"5%",cat:"5%"},{item:"Goods Transport (GTA)",hsn:"9965",rate:"5%",cat:"5%"},{item:"Cab Aggregator (Ola/Uber)",hsn:"9964",rate:"5%",cat:"5%"},{item:"Restaurant (all — no ITC)",hsn:"9963",rate:"5%",cat:"5%"},{item:"Restaurant in Hotel <₹7,500",hsn:"9963",rate:"5%",cat:"5%"},{item:"Tour Operator Services",hsn:"9985",rate:"5%",cat:"5%"},{item:"Hotel (₹1,001 to ₹7,500/night — no ITC)",hsn:"9963",rate:"5%",cat:"5%"},{item:"Fly Ash Bricks / Blocks",hsn:"6815",rate:"5%",cat:"5%"},{item:"Renewable Energy Devices",hsn:"8419",rate:"5%",cat:"5%"},{item:"Electric Two-wheelers",hsn:"8711",rate:"5%",cat:"5%"},{item:"Marble / Granite (raw blocks)",hsn:"2515-2516",rate:"5%",cat:"5%"},{item:"Food Delivery via Aggregator (Swiggy/Zomato)",hsn:"9963",rate:"5%",cat:"5%"},{item:"Commercial Vehicle 3rd Party Insurance",hsn:"9971",rate:"5%",cat:"5%"},
// === 18% — Notf 01/2017-CT(Rate) Sch III as amended by 09/2025-CT(Rate) ===
{item:"Cement (moved from 28%)",hsn:"2523",rate:"18%",cat:"18%"},{item:"Air Conditioners (moved from 28%)",hsn:"8415",rate:"18%",cat:"18%"},{item:"Washing Machines (moved from 28%)",hsn:"8450",rate:"18%",cat:"18%"},{item:"Refrigerator (moved from 28%)",hsn:"8418",rate:"18%",cat:"18%"},{item:"TVs — All Sizes (moved from 28%)",hsn:"8528",rate:"18%",cat:"18%"},{item:"Dishwashers (moved from 28%)",hsn:"8422",rate:"18%",cat:"18%"},{item:"Cars / Small Vehicles (≤1200cc petrol / ≤1500cc diesel)",hsn:"8703",rate:"18%",cat:"18%"},{item:"Motorcycles (≤350cc) (moved from 28%)",hsn:"8711",rate:"18%",cat:"18%"},
{item:"Mobile Phones",hsn:"8517",rate:"18%",cat:"18%"},{item:"Computers / Laptops",hsn:"8471",rate:"18%",cat:"18%"},{item:"Printers / Monitors",hsn:"8443/8528",rate:"18%",cat:"18%"},{item:"Iron & Steel",hsn:"7206-7229",rate:"18%",cat:"18%"},{item:"Aluminium Products",hsn:"7601-7616",rate:"18%",cat:"18%"},{item:"Copper Products",hsn:"7401-7419",rate:"18%",cat:"18%"},{item:"Plastic Products",hsn:"3916-3926",rate:"18%",cat:"18%"},{item:"Rubber Products",hsn:"4001-4017",rate:"18%",cat:"18%"},{item:"Paper / Stationery",hsn:"4801-4823",rate:"18%",cat:"18%"},{item:"Furniture",hsn:"9401-9404",rate:"18%",cat:"18%"},{item:"Mattress",hsn:"9404",rate:"18%",cat:"18%"},{item:"Fans / Coolers",hsn:"8414",rate:"18%",cat:"18%"},{item:"Electrical Machinery",hsn:"8501-8548",rate:"18%",cat:"18%"},{item:"Paints / Varnishes",hsn:"3208-3214",rate:"18%",cat:"18%"},{item:"Tyres / Tubes",hsn:"4011-4013",rate:"18%",cat:"18%"},{item:"Batteries",hsn:"8506-8507",rate:"18%",cat:"18%"},{item:"CCTV / Cameras",hsn:"8525",rate:"18%",cat:"18%"},{item:"Speakers / Headphones",hsn:"8518",rate:"18%",cat:"18%"},
{item:"Footwear (> ₹2,500)",hsn:"6401-6405",rate:"18%",cat:"18%"},{item:"Apparel (> ₹2,500)",hsn:"6101-6117",rate:"18%",cat:"18%"},{item:"Sewing Machines",hsn:"8452",rate:"18%",cat:"18%"},{item:"Umbrella",hsn:"6601",rate:"18%",cat:"18%"},{item:"Suitcase / Bags",hsn:"4202",rate:"18%",cat:"18%"},{item:"Exercise Books / Notebooks",hsn:"4820",rate:"18%",cat:"18%"},{item:"Toys / Games",hsn:"9503",rate:"18%",cat:"18%"},{item:"Kitchen Gas Stoves",hsn:"7321",rate:"18%",cat:"18%"},{item:"Marble / Granite (polished slabs/tiles)",hsn:"6802",rate:"18%",cat:"18%"},{item:"Fireworks / Crackers",hsn:"3604",rate:"18%",cat:"18%"},
{item:"IT / Software Services",hsn:"9983",rate:"18%",cat:"18%"},{item:"Professional / Consulting",hsn:"9983",rate:"18%",cat:"18%"},{item:"Legal / Accounting Services",hsn:"9982",rate:"18%",cat:"18%"},{item:"Telecom Services",hsn:"9984",rate:"18%",cat:"18%"},{item:"Banking / Financial Services",hsn:"9971",rate:"18%",cat:"18%"},{item:"Motor Insurance (Non-Life)",hsn:"9971",rate:"18%",cat:"18%"},{item:"Group Health / Life Insurance",hsn:"9971",rate:"18%",cat:"18%"},{item:"Renting of Immovable Property",hsn:"9972",rate:"18%",cat:"18%"},{item:"Construction (Non-affordable)",hsn:"9954",rate:"18%",cat:"18%"},{item:"Works Contract (Private)",hsn:"9954",rate:"18%",cat:"18%"},{item:"Manpower Supply / Security",hsn:"9985",rate:"18%",cat:"18%"},{item:"Advertising Services",hsn:"9983",rate:"18%",cat:"18%"},{item:"Courier / Postal Services",hsn:"9968",rate:"18%",cat:"18%"},{item:"Hotel (> ₹7,500/night — with ITC)",hsn:"9963",rate:"18%",cat:"18%"},{item:"Restaurant in Hotel ≥₹7,500 (with ITC)",hsn:"9963",rate:"18%",cat:"18%"},{item:"Business Class Air",hsn:"9964",rate:"18%",cat:"18%"},{item:"Printing Services",hsn:"9989",rate:"18%",cat:"18%"},{item:"Works Contract (Govt)",hsn:"9954",rate:"18%",cat:"18%"},{item:"Gym / Fitness Services",hsn:"9996",rate:"18%",cat:"18%"},{item:"Event Management",hsn:"9985",rate:"18%",cat:"18%"},{item:"Photography / Videography",hsn:"9989",rate:"18%",cat:"18%"},{item:"Food Delivery Charges (platform fee)",hsn:"9965",rate:"18%",cat:"18%"},
// === 28% — Tobacco & Luxury Cosmetics (retained) ===
{item:"Tobacco / Cigarettes",hsn:"2402",rate:"28%",cat:"28%"},{item:"Pan Masala / Gutkha",hsn:"2106",rate:"28%",cat:"28%"},{item:"Perfumes / Deodorants",hsn:"3303",rate:"28%",cat:"28%"},{item:"Luxury Cosmetics / Makeup",hsn:"3304",rate:"28%",cat:"28%"},{item:"Sunscreen (premium)",hsn:"3304",rate:"28%",cat:"28%"},
// === 28% + Compensation Cess (GST Compensation to States Act 2017) ===
{item:"Aerated / Carbonated Drinks (28% + 12% Cess)",hsn:"2202",rate:"28%+Cess",cat:"28%"},{item:"Motorcycles > 350cc (28% + 3% Cess)",hsn:"8711",rate:"28%+Cess",cat:"28%"},{item:"Private Yachts (28% + Cess)",hsn:"8903",rate:"28%+Cess",cat:"28%"},{item:"Private Aircraft (28% + Cess)",hsn:"8802",rate:"28%+Cess",cat:"28%"},{item:"Gambling / Betting / Casino (28%)",hsn:"9996",rate:"28%",cat:"28%"},{item:"Online Gaming (28% on full face value)",hsn:"9996",rate:"28%",cat:"28%"},
// === NON-GST (Outside GST — State VAT / Central Excise) ===
{item:"Petrol / Motor Spirit (MS)",hsn:"2710.1210",rate:"Non-GST",cat:"Non-GST"},{item:"High Speed Diesel (HSD)",hsn:"2710.1930",rate:"Non-GST",cat:"Non-GST"},{item:"Aviation Turbine Fuel (ATF)",hsn:"2710.1920",rate:"Non-GST",cat:"Non-GST"},{item:"Natural Gas",hsn:"2711.1100",rate:"Non-GST",cat:"Non-GST"},{item:"Crude Oil / Petroleum Crude",hsn:"2709",rate:"Non-GST",cat:"Non-GST"},{item:"Liquor for Human Consumption",hsn:"2208",rate:"Non-GST",cat:"Non-GST"},{item:"Electricity",hsn:"2716",rate:"Non-GST",cat:"Non-GST"}
];
var activeGSTFilter='all';
function searchGST(){var q=document.getElementById('gstSearch').value.toLowerCase(),c=document.getElementById('gstResults');
var f=gstItems;if(activeGSTFilter!=='all')f=f.filter(function(g){return g.cat===activeGSTFilter;});
if(q)f=f.filter(function(g){return (g.item+g.hsn+g.rate+g.cat).toLowerCase().indexOf(q)>=0;});
c.innerHTML=f.map(function(g){var color=g.rate==='0%'?'var(--success)':g.rate==='5%'?'#0a8c64':g.rate==='18%'?'#b5651d':g.rate==='28%'?'#d63031':g.rate==='28%+Cess'?'#6c5ce7':g.rate==='Non-GST'?'#8e44ad':'#e17055';
var note=g.rate==='Non-GST'?'<span style="color:#8e44ad;font-size:0.78rem;font-weight:600;"> — Outside GST | State VAT / Central Excise applicable</span>':'';
var moved=g.item.indexOf('moved from')>=0?'<span style="color:#e17055;font-size:0.75rem;font-weight:600;"> ⚡ Rate Changed</span>':'';
var newItem=g.item.indexOf('NEW')>=0?'<span style="color:var(--success);font-size:0.75rem;font-weight:600;"> ✦ New</span>':'';
return '<div class="gst-item"><div class="gst-rate" style="color:'+color+'">'+g.rate+'</div><div class="gst-info"><strong>'+g.item+'</strong>'+note+moved+newItem+'<p>HSN/SAC: '+g.hsn+' | '+g.cat+'</p></div></div>';}).join('');
if(!f.length)c.innerHTML='<p style="text-align:center;color:var(--text-light);padding:20px;">No items found. Try a different keyword or HSN code.</p>';}
function filterGST(cat,btn){document.querySelectorAll('#gstFilterRow .filter-btn').forEach(function(b){b.classList.remove('active');});btn.classList.add('active');activeGSTFilter=cat;searchGST();}
searchGST();


// ==================== GST REGISTRATION JS ====================
function checkGSTReg(){
var state=document.getElementById('gstState').value;
var type=document.getElementById('gstType').value;
var nature=document.getElementById('gstNature').value;
var turnover=parseFloat(document.getElementById('gstTurnover').value)||0;
var exempt=document.getElementById('gstExempt').value;
var interstate=document.getElementById('gstInterstate').value;
var r=document.getElementById('gstRegResult');
var isSpecial=(state==='special');
var threshold=0;
if(nature==='goods')threshold=isSpecial?2000000:4000000;
else threshold=isSpecial?1000000:2000000;
var mandatoryTypes=['ecom_seller','ecom_operator','casual','nri','isd','tds51','tcs52','interstate_goods','oidar'];
var isMandatoryType=mandatoryTypes.indexOf(type)>=0;
var isMandatoryInterstate=(interstate==='yes');
var isMandatoryTurnover=(turnover>threshold);
var isExempt=(type==='agriculturist'||(exempt==='exempt'&&!isMandatoryInterstate&&!isMandatoryType));
var reason='';
r.className='result-box presumptive';
var html='';
if(isExempt){
html='<div class="result-title" style="color:#00b894;">EXEMPT FROM REGISTRATION</div><div class="result-detail">';
html+='<table class="limits-table"><tr><td>Status</td><td style="color:#00b894;font-weight:700;">Exempt from GST registration</td></tr>';
html+='<tr><td>Section</td><td>Section 23, CGST Act 2017</td></tr>';
html+='<tr><td>Note</td><td>If you later make any taxable supply or cross the threshold, registration becomes mandatory.</td></tr></table></div>';
}else if(isMandatoryType||isMandatoryInterstate||isMandatoryTurnover){
if(isMandatoryType){
var typeReasons={ecom_seller:'Seller through e-commerce platform — Sec 24(ix)',ecom_operator:'E-commerce operator — Sec 24(x)',casual:'Casual taxable person — Sec 24(ii)',nri:'Non-resident taxable person — Sec 24(v)',isd:'Input Service Distributor — Sec 24(iv)',tds51:'TDS deductor u/s 51 — Sec 24(vi)',tcs52:'TCS collector u/s 52 — Sec 24(x)',interstate_goods:'Inter-state supply of goods — Sec 24(i)',oidar:'OIDAR from outside India — Sec 24(xi)'};
reason=typeReasons[type]||'Mandatory category';
}else if(isMandatoryInterstate){reason='Inter-state supply of goods — Sec 24(i)';}
else{reason='Turnover Rs '+fmt(turnover)+' exceeds threshold Rs '+fmt(threshold)+' — Sec 22';}
html='<div class="result-title" style="color:#d63031;">MANDATORY REGISTRATION REQUIRED</div><div class="result-detail">';
html+='<table class="limits-table"><tr><td>Applicable threshold</td><td>Rs '+fmt(threshold)+'</td></tr>';
html+='<tr><td>Your turnover</td><td>Rs '+fmt(turnover)+'</td></tr>';
html+='<tr><td>Reason</td><td style="color:#d63031;font-weight:600;">'+reason+'</td></tr>';
html+='<tr><td>Action required</td><td>Register on GST Portal (gst.gov.in) within 30 days of becoming liable</td></tr></table></div>';
}else{
html='<div class="result-title" style="color:#f39c12;">VOLUNTARY REGISTRATION AVAILABLE</div><div class="result-detail">';
html+='<table class="limits-table"><tr><td>Your turnover</td><td>Rs '+fmt(turnover)+'</td></tr>';
html+='<tr><td>Threshold</td><td>Rs '+fmt(threshold)+'</td></tr>';
html+='<tr><td>Status</td><td>Registration is NOT mandatory but you may voluntarily register</td></tr>';
html+='<tr><td>Benefits</td><td>Can claim ITC, issue tax invoices, do inter-state business freely</td></tr>';
html+='<tr><td>Section</td><td>Section 25(3), CGST Act 2017</td></tr></table></div>';
}
r.innerHTML=html;
}
function resetGSTReg(){document.getElementById('gstTurnover').value='';document.getElementById('gstType').value='regular';document.getElementById('gstNature').value='goods';document.getElementById('gstExempt').value='taxable';document.getElementById('gstInterstate').value='no';document.getElementById('gstRegResult').className='result-box';document.getElementById('gstRegResult').innerHTML='';}




// ==============================
// GST COMPOSITION SCHEME — Sec 10, CGST Act 2017
// ==============================
function checkCompositionEligibility() {
  var turnover = parseFloat(document.getElementById('compTurnover').value) || 0;
  var state    = document.getElementById('compState').value;
  var business = document.getElementById('compBusiness').value;
  var inter    = document.getElementById('compInterstate').value;
  var ecom     = document.getElementById('compEcom').value;
  var excl     = document.getElementById('compExcluded').value;
  var casual   = document.getElementById('compCasual').value;
  var div      = document.getElementById('compResult');

  div.style.display = 'block';
  div.scrollIntoView({ behavior: 'smooth', block: 'nearest' });

  if (!turnover || turnover <= 0) {
    div.innerHTML = '<div style="background:#fff3e0;border:2px solid #ff9800;border-radius:8px;padding:14px;">⚠️ Please enter your Annual Aggregate Turnover.</div>';
    return;
  }
  if (!business) {
    div.innerHTML = '<div style="background:#fff3e0;border:2px solid #ff9800;border-radius:8px;padding:14px;">⚠️ Please select Nature of Business.</div>';
    return;
  }

  if (inter === 'yes')  { showCompNo(div, 'Makes inter-state outward supply of goods', 'Section 10(2)(a), CGST Act 2017', 'Composition scheme is only for intra-state suppliers.'); return; }
  if (ecom === 'yes')   { showCompNo(div, 'Supplies through e-commerce operator (Amazon/Flipkart/Swiggy/Zomato)', 'Section 10(2)(d), CGST Act 2017', 'Sellers on e-commerce platforms cannot opt for composition scheme.'); return; }
  if (excl === 'yes')   { showCompNo(div, 'Manufacturer of Ice Cream / Pan Masala / Tobacco', 'Section 10(2)(e), CGST Act 2017', 'These specific goods are excluded regardless of turnover.'); return; }
  if (casual === 'yes') { showCompNo(div, 'Casual or Non-Resident Taxable Person', 'Section 10(2)(b), CGST Act 2017', 'Must register as regular dealer.'); return; }

  var limit, rate, cgst, sgst, rateNote, returns;
  if (business === 'service') {
    limit = 5000000;
    rate = '6%'; cgst = '3%'; sgst = '3%';
    rateNote = 'Section 10(2A), CGST Act. Service supply must not exceed 10% of turnover in preceding FY or Rs 5 lakh — whichever is higher.';
    returns = 'CMP-08 quarterly (by 18th of next month) + GSTR-4 annually (by 30 April)';
  } else if (business === 'restaurant') {
    limit = (state === 'special') ? 7500000 : 15000000;
    rate = '5%'; cgst = '2.5%'; sgst = '2.5%';
    rateNote = 'Restaurants not serving alcohol — Section 10(1)(b), CGST Act.';
    returns = 'CMP-08 quarterly + GSTR-4 annually (by 30 April)';
  } else if (business === 'mixed') {
    limit = (state === 'special') ? 7500000 : 15000000;
    rate = '6%'; cgst = '3%'; sgst = '3%';
    rateNote = 'Mixed supply taxed at 6% under Section 10(2A), CGST Act.';
    returns = 'CMP-08 quarterly + GSTR-4 annually (by 30 April)';
  } else {
    limit = (state === 'special') ? 7500000 : 15000000;
    rate = '1%'; cgst = '0.5%'; sgst = '0.5%';
    rateNote = 'Manufacturers and traders — Section 10(1)(a), CGST Act.';
    returns = 'CMP-08 quarterly (by 18th of next month) + GSTR-4 annually (by 30 April)';
  }

  if (turnover > limit) {
    showCompNo(div,
      'Turnover Rs ' + turnover.toLocaleString('en-IN') + ' exceeds limit of Rs ' + limit.toLocaleString('en-IN'),
      'Section 10(1)/(2A), CGST Act | Notification No. 14/2019-CT',
      'Must register as a Regular Dealer. See GST Registration tab.'
    ); return;
  }

  showCompYes(div, turnover, limit, rate, cgst, sgst, rateNote, returns, state);
}

function showCompYes(div, turnover, limit, rate, cgst, sgst, rateNote, returns, state) {
  div.innerHTML =
    '<div style="background:#e8f8f5;border:2px solid #00b894;border-radius:8px;padding:16px;">' +
    '<h4 style="color:#00b894;margin:0 0 14px;">✅ ELIGIBLE FOR COMPOSITION SCHEME</h4>' +
    '<div class="table-scroll"><table class="limits-table" style="width:100%;font-size:0.9rem;">' +
    '<tr style="background:#f0faf8;"><td style="font-weight:600;width:45%">Your Turnover</td><td>Rs ' + turnover.toLocaleString('en-IN') + '</td></tr>' +
    '<tr><td style="font-weight:600;">Applicable Limit</td><td>Rs ' + limit.toLocaleString('en-IN') + ' (' + (state==='special'?'Special Category State':'Normal State') + ')</td></tr>' +
    '<tr style="background:#f0faf8;"><td style="font-weight:600;">GST Rate</td><td style="font-weight:700;color:#00695c;">' + rate + ' total — CGST ' + cgst + ' + SGST ' + sgst + '</td></tr>' +
    '<tr><td style="font-weight:600;">Returns</td><td>' + returns + '</td></tr>' +
    '<tr style="background:#f0faf8;"><td style="font-weight:600;">Opt-In Form</td><td>Form CMP-02 on gst.gov.in — file by <strong>31 March</strong> of preceding year</td></tr>' +
    '<tr><td style="font-weight:600;">Invoice</td><td>Bill of Supply only — <strong>cannot issue Tax Invoice</strong></td></tr>' +
    '<tr style="background:#f0faf8;"><td style="font-weight:600;">Input Tax Credit</td><td><strong>Not available</strong> — cannot claim ITC on any purchases</td></tr>' +
    '<tr><td style="font-weight:600;">Section</td><td>Section 10, CGST Act 2017 | Rule 7, CGST Rules 2017</td></tr>' +
    '</table></div>' +
    '<p style="margin:12px 0 4px;font-size:0.82rem;color:#e67e22;"><strong>Note:</strong> ' + rateNote + '</p>' +
    '<p style="margin:4px 0;font-size:0.82rem;color:#e67e22;">⚠️ Tax paid from cash ledger only — ITC cannot be used to pay composition tax.</p>' +
    '<p style="margin:4px 0;font-size:0.82rem;color:#e67e22;">⚠️ Must display "Composition taxable person, not eligible to collect tax on supplies" at business premises.</p>' +
    '</div>';
}

function showCompNo(div, reason, section, detail) {
  div.innerHTML =
    '<div style="background:#fdecea;border:2px solid #e74c3c;border-radius:8px;padding:16px;">' +
    '<h4 style="color:#c0392b;margin:0 0 10px;">❌ NOT ELIGIBLE FOR COMPOSITION SCHEME</h4>' +
    '<p style="margin:0 0 6px;"><strong>Reason:</strong> ' + reason + '</p>' +
    '<p style="margin:0 0 6px;"><strong>Section:</strong> ' + section + '</p>' +
    '<p style="margin:0;font-size:0.85rem;color:#555;">' + detail + '</p>' +
    '</div>';
}

function resetComposition() {
  var t = document.getElementById('compTurnover'); if (t) t.value = '';
  ['compState','compBusiness','compInterstate','compEcom','compExcluded','compCasual'].forEach(function(id){
    var el = document.getElementById(id); if (el) el.selectedIndex = 0;
  });
  var r = document.getElementById('compResult');
  if (r) { r.style.display = 'none'; r.innerHTML = ''; }
}
