// js/main.js — extracted from index.html
// Generated by split.cjs

// ==============================
// UTILITY
// ==============================
function switchTab(t){document.querySelectorAll('.tab-content').forEach(e=>e.classList.remove('active'));document.querySelectorAll('.nav-tab').forEach(e=>e.classList.remove('active'));document.getElementById('tab-'+t).classList.add('active');var tabs=document.querySelectorAll('.nav-tab');for(var i=0;i<tabs.length;i++){if(tabs[i].textContent.trim()&&tabs[i].getAttribute('onclick')&&tabs[i].getAttribute('onclick').indexOf("'"+t+"'")>-1){tabs[i].classList.add('active');break;}}}
function fmt(n){return new Intl.NumberFormat('en-IN').format(n);}
function escapeHTML(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}

// Auto-add Last Updated footer to all tabs
document.querySelectorAll('.tab-content').forEach(function(tab){
if(tab.id==='tab-home')return;
var ft=document.createElement('p');
ft.style.cssText='text-align:center;font-size:0.72rem;color:#999;margin-top:20px;padding-top:10px;border-top:1px solid #eee;';
ft.textContent='Last Updated: April 2026';
tab.appendChild(ft);
});

// Render penalty table on load
searchPenalty();

renderDueDates();

// ==================== MOBILE: Wrap all tables in scroll containers ====================
document.querySelectorAll('.limits-table').forEach(function(table){
  if(table.parentElement.classList.contains('table-scroll'))return;
  var wrapper=document.createElement('div');
  wrapper.className='table-scroll';
  table.parentNode.insertBefore(wrapper,table);
  wrapper.appendChild(table);
});

// Re-wrap dynamically generated tables after search/filter actions
var origSearchPenalty=searchPenalty;
searchPenalty=function(){origSearchPenalty();document.querySelectorAll('#penaltyResults .limits-table').forEach(function(t){if(!t.parentElement.classList.contains('table-scroll')){var w=document.createElement('div');w.className='table-scroll';t.parentNode.insertBefore(w,t);w.appendChild(t);}});};
var origRule37BB=searchRule37BB;
searchRule37BB=function(){origRule37BB();document.querySelectorAll('#rule37bbResults .limits-table').forEach(function(t){if(!t.parentElement.classList.contains('table-scroll')){var w=document.createElement('div');w.className='table-scroll';t.parentNode.insertBefore(w,t);w.appendChild(t);}});};

// ==================== FAVOURITES (BOOKMARKS) ====================
var FAV_KEY='rr_favourites';
function _favGet(){try{return JSON.parse(localStorage.getItem(FAV_KEY)||'[]');}catch(e){return [];}}
function _favSet(arr){try{localStorage.setItem(FAV_KEY,JSON.stringify(arr));}catch(e){}}
function _tabMeta(tabId){
  // Find the matching home-page nav card for icon + label, fall back to nav-tab text
  // Match welcome card / tab-guide row, but NOT a fav-card (which also has the same onclick)
  var candidates=document.querySelectorAll("#tab-home [onclick*=\"switchTab('"+tabId+"')\"]");
  var navCard=null;
  for(var i=0;i<candidates.length;i++){if(!candidates[i].closest('#favSection')){navCard=candidates[i];break;}}
  var icon='⭐',label=tabId;
  if(navCard){
    var iconEl=navCard.querySelector('div[style*="font-size:1.8rem"]');
    var labelEl=navCard.querySelector('div[style*="font-weight:700"]');
    if(iconEl)icon=iconEl.textContent.trim();
    if(labelEl)label=labelEl.textContent.trim();
  }else{
    var navTab=Array.from(document.querySelectorAll('.nav-tab')).find(function(nt){var oc=nt.getAttribute('onclick')||'';return oc.indexOf("'"+tabId+"'")>-1;});
    if(navTab)label=navTab.textContent.trim();
  }
  return {icon:icon,label:label};
}
function toggleFavourite(tabId,btn){
  var arr=_favGet();
  var idx=arr.indexOf(tabId);
  if(idx>-1){arr.splice(idx,1);}else{arr.push(tabId);}
  _favSet(arr);
  if(btn){
    if(idx>-1){btn.classList.remove('active');btn.innerHTML='☆';btn.title='Add to favourites';}
    else{btn.classList.add('active');btn.innerHTML='★';btn.title='Remove from favourites';}
  }
  renderFavourites();
}
function removeFavourite(tabId,ev){
  if(ev){ev.stopPropagation();}
  var arr=_favGet();
  var idx=arr.indexOf(tabId);
  if(idx>-1){arr.splice(idx,1);_favSet(arr);}
  // sync any star buttons
  var btn=document.querySelector('.fav-btn[data-tab="'+tabId+'"]');
  if(btn){btn.classList.remove('active');btn.innerHTML='☆';btn.title='Add to favourites';}
  renderFavourites();
}
function renderFavourites(){
  var sec=document.getElementById('favSection');
  var list=document.getElementById('favList');
  if(!sec||!list)return;
  var arr=_favGet();
  if(arr.length===0){sec.style.display='none';list.innerHTML='';return;}
  sec.style.display='block';
  list.innerHTML=arr.map(function(tabId){
    var m=_tabMeta(tabId);
    return '<div class="fav-card" onclick="switchTab(\''+tabId+'\')">'+
      '<button class="fav-remove" onclick="removeFavourite(\''+tabId+'\',event)" title="Remove">✕</button>'+
      '<div class="fav-icon">'+escapeHTML(m.icon)+'</div>'+
      '<div class="fav-label">'+escapeHTML(m.label)+'</div></div>';
  }).join('');
}
function loadFavourites(){
  var arr=_favGet();
  // Inject star button next to every tab's first H2 (except home)
  document.querySelectorAll('.tab-content').forEach(function(tab){
    if(tab.id==='tab-home')return;
    var h2=tab.querySelector('h2');
    if(!h2||h2.querySelector('.fav-btn'))return;
    var tabId=tab.id.replace('tab-','');
    var isFav=arr.indexOf(tabId)>-1;
    var btn=document.createElement('button');
    btn.className='fav-btn'+(isFav?' active':'');
    btn.setAttribute('data-tab',tabId);
    btn.innerHTML=isFav?'★':'☆';
    btn.title=isFav?'Remove from favourites':'Add to favourites';
    btn.onclick=function(e){e.stopPropagation();toggleFavourite(tabId,btn);};
    h2.appendChild(btn);
  });
  renderFavourites();
}
loadFavourites();

// ==================== COPY / PRINT RESULT ====================
function copyResult(resultId,btn){
  var el=document.getElementById(resultId);
  if(!el)return;
  var text=el.innerText||el.textContent||'';
  if(navigator.clipboard&&navigator.clipboard.writeText){
    navigator.clipboard.writeText(text).then(function(){
      if(btn){var orig=btn.textContent;btn.textContent='✓ Copied';btn.classList.add('copied');setTimeout(function(){btn.textContent=orig;btn.classList.remove('copied');},1500);}
    }).catch(function(){_fallbackCopy(text,btn);});
  }else{_fallbackCopy(text,btn);}
}
function _fallbackCopy(text,btn){
  var ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();
  try{document.execCommand('copy');if(btn){var o=btn.textContent;btn.textContent='✓ Copied';btn.classList.add('copied');setTimeout(function(){btn.textContent=o;btn.classList.remove('copied');},1500);}}catch(e){}
  document.body.removeChild(ta);
}
function printResult(resultId){
  var el=document.getElementById(resultId);
  if(!el)return;
  var w=window.open('','_blank','width=800,height=600');
  if(!w){alert('Please allow popups to print.');return;}
  var html='<!doctype html><html><head><meta charset="utf-8"><title>Ready Reckoner — Result</title>'+
    '<style>body{font-family:Arial,sans-serif;padding:24px;color:#222;max-width:780px;margin:0 auto;}'+
    'h1{color:#203a43;font-size:1.4rem;margin:0 0 4px;}'+
    '.brand{border-bottom:2px solid #203a43;padding-bottom:10px;margin-bottom:16px;}'+
    '.brand .sub{color:#666;font-size:0.85rem;}'+
    'table{border-collapse:collapse;width:100%;margin:8px 0;font-size:0.88rem;}'+
    'th,td{border:1px solid #ccc;padding:6px 8px;text-align:left;vertical-align:top;}'+
    'th{background:#f5f7fa;}'+
    'h4{margin:10px 0 6px;color:#203a43;}'+
    '.foot{margin-top:24px;padding-top:10px;border-top:1px solid #ccc;font-size:0.74rem;color:#777;text-align:center;}'+
    '@media print{button{display:none;}}'+
    '</style></head><body>'+
    '<div class="brand"><h1>Ready Reckoner — CA Toolkit</h1>'+
    '<div class="sub">CA Deepak Patni &nbsp;|&nbsp; readyreckonercadeepakpatni.netlify.app &nbsp;|&nbsp; '+new Date().toLocaleString('en-IN')+'</div></div>'+
    '<div>'+el.innerHTML+'</div>'+
    '<div class="foot">Generated from Ready Reckoner. Verify with the latest official notifications before relying on these figures.</div>'+
    '<script>window.onload=function(){window.print();};<\/script>'+
    '</body></html>';
  w.document.open();w.document.write(html);w.document.close();
}
// Inject Copy/Print action bars below every result-style div on first appearance
function ensureResultActions(){
  // result IDs to instrument (curated list)
  var ids=['itResult','emiResult','gstResults','mappingResults','depResult','depCoResult','msmeResult','noticeResult','caroResult','asClassResult','cgResult','cgExResult','ipResult','imResult','itrResult','fcResult','penaltyResults','pResult','itruResult','adResult','adaResult','aeResult','gstRegResult','rfResult','rocPenResult','compResult','rule37bbResults'];
  ids.forEach(function(id){
    var el=document.getElementById(id);if(!el)return;
    if(document.getElementById('actions-'+id))return;
    var bar=document.createElement('div');
    bar.className='result-actions';bar.id='actions-'+id;
    bar.innerHTML='<button onclick="copyResult(\''+id+'\',this)">📋 Copy Result</button>'+
                  '<button onclick="printResult(\''+id+'\')">🖨️ Print Result</button>';
    el.parentNode.insertBefore(bar,el.nextSibling);
    // observe el for content changes → show bar
    var showIfHasContent=function(){
      var hasContent=el.innerHTML.trim().length>0&&(el.style.display==='' ||el.style.display==='block'||!el.style.display||el.offsetHeight>0);
      bar.classList.toggle('show',hasContent);
    };
    showIfHasContent();
    var mo=new MutationObserver(showIfHasContent);
    mo.observe(el,{childList:true,subtree:true,attributes:true,attributeFilter:['style']});
  });
}
ensureResultActions();

// ==================== BACK TO TOP BUTTON ====================
(function(){
  var btn=document.createElement('button');
  btn.id='backToTop';
  btn.innerHTML='&#8679;';
  btn.title='Back to Top';
  document.body.appendChild(btn);
  window.addEventListener('scroll',function(){
    btn.style.display=window.scrollY>400?'block':'none';
  });
  btn.addEventListener('click',function(){
    window.scrollTo({top:0,behavior:'smooth'});
  });
})();

