// js/smartsearch.js — extracted from index.html
// Generated by split.cjs

// ==============================
var smartDB=[
{q:"cash payment above 10000 10k 40a",topic:"Cash Payment > Rs 10,000",impacts:[
{area:"Income Tax",detail:"100% disallowance u/s 40A(3). Exception: transporters Rs 35,000 (Rule 6DD). New Act: equivalent provision in Chapter V."},
{area:"Form 3CD",detail:"Report in <strong>Clause 32</strong> (Form 3CD) / Clause 31-33 (Form 26). Each payment to be listed separately."},
{area:"Tax Audit",detail:"Auditor must scan entire cash book and flag all payments >10K. Common audit observation."},
{area:"Penalty",detail:"No separate penalty — but disallowance increases taxable income and tax liability."},
{area:"Practical Tip",detail:"Check Rule 6DD exceptions: medical emergency, villages without banks, agriculture. Transporters can pay up to Rs 35,000 in cash."}
]},
{q:"cash receipt 2 lakh 269st cash received",topic:"Cash Receipt > Rs 2 Lakh — Sec 269ST",impacts:[
{area:"Income Tax",detail:"Penalty u/s 271DA = 100% of amount received. Sec 269ST prohibits cash receipt >2L from a person in a day / single transaction / related to one event."},
{area:"Form 3CD",detail:"Report in <strong>Clause 31</strong> (Enhanced AY 2025-26). Transaction codes required."},
{area:"GST",detail:"No direct GST impact, but large cash transactions may trigger scrutiny."},
{area:"Practical Tip",detail:"Watch for split transactions designed to evade the limit. Aggregate per person per day."}
]},
{q:"esic esi employee state insurance",topic:"ESIC / ESI Contribution",impacts:[
{area:"Income Tax",detail:"Deductible u/s 36(1)(va) only if deposited before employee's contribution due date. Employer's share: u/s 43B."},
{area:"Form 3CD",detail:"Report in <strong>Clause 26</strong> (Sec 43B items) if deposited late. Also check Clause 20 (deductions)."},
{area:"Section 43B",detail:"Must be PAID before return filing due date to claim deduction. Late deposit = disallowance."},
{area:"Employee Contribution",detail:"If employee's share deducted but not deposited by ESI due date → permanent disallowance u/s 36(1)(va) per Supreme Court in Checkmate Services."},
{area:"Penalty",detail:"ESI Act penalties + IT disallowance. Interest u/s 234B/C may apply on additional tax."},
{area:"Practical Tip",detail:"ESI applicable if wages ≤ Rs 21,000/month. Employer: 3.25%, Employee: 0.75%. Due by 15th of next month."}
]},
{q:"pf provident fund epf employer employee",topic:"Provident Fund (PF/EPF)",impacts:[
{area:"Income Tax",detail:"Employer's contribution deductible u/s 36(1)(iv). Employee's share: u/s 36(1)(va) — must deposit by PF due date (15th of next month)."},
{area:"Form 3CD",detail:"Report in <strong>Clause 26</strong> (Sec 43B). Late deposits to be specifically reported with dates."},
{area:"Supreme Court",detail:"Checkmate Services Pvt Ltd (2022) — Employee's contribution NOT covered by 43B grace period. Must deposit by statutory due date."},
{area:"Practical Tip",detail:"PF due by 15th of next month. Annual return by 25th April. Employer 12% (3.67% EPF + 8.33% EPS), Employee 12%."}
]},
{q:"tds rent 194i 194ib",topic:"TDS on Rent",impacts:[
{area:"Income Tax — 194I",detail:"TDS @ 2% (plant/machinery/equipment) or 10% (land/building/furniture). Threshold: Rs 2,40,000 p.a."},
{area:"Income Tax — 194IB",detail:"For individuals/HUF not liable to audit: TDS @ 5% if rent > Rs 50,000/month. Deduct in last month of FY."},
{area:"Form 3CD",detail:"Report in <strong>Clause 34</strong> (TDS compliance). Non-deduction → 30% disallowance u/s 40(a)(ia)."},
{area:"New Act 2025",detail:"Sec 194I → Sec 406 (approx). Rates expected to remain same."},
{area:"GST",detail:"GST @ 18% on commercial rent (RCM if from unregistered landlord to registered tenant). Residential rent by registered person: 18% under RCM."},
{area:"Practical Tip",detail:"If landlord is NR: TDS u/s 195 (not 194I). DTAA rates may apply. Obtain TRC + Form 10F."}
]},
{q:"msme payment 43b micro small enterprise vendor",topic:"MSME Payment — Sec 43B(h)",impacts:[
{area:"Income Tax",detail:"Payment to Micro/Small enterprises must be within agreed time (max 45 days, or 15 days if no agreement). Otherwise DISALLOWED u/s 43B(h)."},
{area:"Form 3CD",detail:"Report in <strong>Clause 22</strong> (Enhanced) — Udyam verification, interest u/s 23 MSMED Act. Also Clause 26 (43B items)."},
{area:"MSMED Act",detail:"Interest @ 3x bank rate (compound monthly) payable on delayed payment. Not deductible."},
{area:"Companies Act",detail:"MSME dues to be reported in financial statements under Schedule III. Interest on delayed payment to be disclosed."},
{area:"Practical Tip",detail:"Verify ALL vendors on Udyam portal. Get declarations. Track payment days. 45-day clock starts from acceptance of goods/services."}
]},
{q:"depreciation asset fixed capitalized",topic:"Depreciation — IT & Companies Act",impacts:[
{area:"Income Tax",detail:"WDV method per Appendix I-A. Rates: Building 10%, Furniture 10%, P&M 15%, Computers 40%, Vehicles 15%. 50% if used <180 days."},
{area:"Companies Act",detail:"SLM or WDV per Schedule II (useful life based). Component accounting applicable."},
{area:"Form 3CD",detail:"Report in <strong>Clause 18</strong> — Complete WDV schedule with additions, deletions, rate applied."},
{area:"Key Difference",detail:"IT depreciation ≠ Book depreciation. Deferred tax (AS 22) arises from timing difference."},
{area:"Practical Tip",detail:"No depreciation on goodwill (IT). Intangible assets: 25% WDV (IT). Keep separate depreciation charts for IT and Co Act."}
]},
{q:"gst input tax credit itc blocked 17",topic:"GST Input Tax Credit (ITC)",impacts:[
{area:"GST Act",detail:"ITC available u/s 16. Must be reflected in GSTR-2B. Blocked credit u/s 17(5): motor vehicles, food/beverages, health/fitness, personal use."},
{area:"Form 3CD",detail:"Report in <strong>Clause 44</strong> — ITC availed, reversed, ineligible. GST reconciliation with GSTR-3B."},
{area:"Income Tax",detail:"If ITC not claimed/reversed → becomes part of cost (capitalize or expense). Impacts P&L."},
{area:"Practical Tip",detail:"Reconcile ITC monthly with GSTR-2B. Reverse ineligible ITC before annual return. Keep documentation for all reversals."}
]},
{q:"loan deposit cash 269ss 269t 20000",topic:"Cash Loans/Deposits > Rs 20,000",impacts:[
{area:"Income Tax",detail:"Sec 269SS: Cannot accept loan/deposit in cash >Rs 20,000. Sec 269T: Cannot repay in cash >Rs 20,000. Penalty: 100% of amount."},
{area:"Form 3CD",detail:"Report in <strong>Clause 30-31</strong>. Enhanced transaction-level reporting with codes from AY 2025-26."},
{area:"Practical Tip",detail:"Applies to loans AND deposits. Partners' capital contributions are covered. Use banking channels."}
]},
{q:"tds professional 194j 194c contractor",topic:"TDS on Professional/Contractor Fees",impacts:[
{area:"Income Tax — 194J",detail:"TDS @ 10% on professional/technical fees. Threshold: Rs 30,000 p.a. Includes CA fees, legal, consultancy, royalty."},
{area:"Income Tax — 194C",detail:"TDS @ 1% (individual/HUF) or 2% (others) on contractor payments. Threshold: Rs 30,000 single / Rs 1,00,000 aggregate."},
{area:"Form 3CD",detail:"Report in <strong>Clause 34</strong> (TDS). Non-deduction → 30% disallowance u/s 40(a)(ia)."},
{area:"Practical Tip",detail:"Distinguish between 194J (professional services) and 194C (works contract). CA/lawyer fees = 194J. Building contractor = 194C. Software development = depends on nature."}
]},
{q:"salary tds 192 employee",topic:"TDS on Salary — Sec 192",impacts:[
{area:"Income Tax",detail:"Employer deducts TDS on estimated annual salary. Consider declarations (rent HRA, 80C, 80D). New regime default from FY 2024-25."},
{area:"Form 16",detail:"Issue by 15 June. Part A (TDS summary) + Part B (detailed computation)."},
{area:"Form 3CD",detail:"Verify TDS on salary in <strong>Clause 34</strong>. Check 26AS/AIS match."},
{area:"Practical Tip",detail:"If employee opts for old regime, get written declaration. Employer can consider HRA, LTA, 80C etc. for TDS computation."}
]},
{q:"related party 40a director relative transaction arm length",topic:"Related Party Transactions — Sec 40A(2)(b)",impacts:[
{area:"Income Tax",detail:"Sec 40A(2)(b): Payments to related parties (directors, partners, relatives, entities with substantial interest) in excess of fair market value can be disallowed by AO."},
{area:"Form 3CD",detail:"Report in <strong>Clause 23</strong> (Form 3CD) / Clause 28-30 (Form 26). List all payments to persons specified in 40A(2)(b) with amounts and nature."},
{area:"Companies Act",detail:"Sec 188 — Related party transactions need Board/Shareholder approval. Arm's length pricing mandatory. Disclosure in Board's report."},
{area:"AS 18 / Ind AS 24",detail:"<strong>AS 18</strong>: Disclosure of related party relationships and transactions. MSME entities may get partial exemption if turnover ≤50Cr & borrowings ≤10Cr."},
{area:"Transfer Pricing",detail:"Sec 92BA: Specified domestic transactions >2Cr require TP documentation. IT Act 2025: Sec 34 (International) & Sec 38 (Domestic)."},
{area:"GST",detail:"Supply to related persons taxable at open market value even if made without consideration. Rule 28 CGST Rules."},
{area:"Practical Tip",detail:"Maintain register of related parties. Compare all transactions with FMV. Get independent valuation for property/shares. Board resolution for each RPT."}
]},
{q:"advance tax installment 207 208 209 210 211",topic:"Advance Tax — Sec 207-211",impacts:[
{area:"Income Tax",detail:"Advance tax payable if tax liability exceeds Rs 10,000. Instalments: 15 Jun (15%), 15 Sep (45%), 15 Dec (75%), 15 Mar (100%)."},
{area:"Interest",detail:"Sec 234B: Interest @1% per month if advance tax paid <90% of assessed tax. Sec 234C: Interest @1% per month for deferment of instalments."},
{area:"Sec 44AD/44ADA",detail:"Presumptive assessees pay 100% advance tax by 15 March in single instalment."},
{area:"Practical Tip",detail:"Compute estimated income quarterly. Pay advance tax on time. Even after 31 Mar, pay before filing return to reduce 234B interest."}
]},
{q:"capital gain property share mutual fund ltcg stcg",topic:"Capital Gains — LTCG / STCG",impacts:[
{area:"Income Tax",detail:"Post 23.07.2024: LTCG uniformly @12.5% (no indexation except grandfathered property). STCG listed equity @20%. Other STCG at slab rates."},
{area:"Exemption",detail:"Sec 54: LTCG on house → reinvest in new house (2 years purchase / 3 years construction). Sec 54EC: Invest in specified bonds within 6 months (max Rs 50L)."},
{area:"Form 3CD",detail:"Report in <strong>Clause 13-14</strong> (capital expenditure). Verify holding period and cost computation."},
{area:"Practical Tip",detail:"For property before 23.07.2024: compute BOTH ways (12.5% without indexation vs 20% with indexation) — pick lower tax."}
]},
{q:"tds interest 194a bank fd deposit",topic:"TDS on Interest — Sec 194A",impacts:[
{area:"Income Tax",detail:"TDS @10% on interest (other than on securities) exceeding Rs 40,000 p.a. (Rs 50,000 for senior citizens) from banks. Rs 5,000 for others."},
{area:"26AS / AIS",detail:"All interest TDS appears in 26AS and AIS. Match with books. Common mismatch area."},
{area:"Form 3CD",detail:"Report in <strong>Clause 34</strong> (TDS compliance). Non-deduction → 30% disallowance u/s 40(a)(ia)."},
{area:"Practical Tip",detail:"Check all FDs, inter-corporate deposits, partner interest, unsecured loans. Form 15G/15H from recipients to avoid TDS."}
]},
{q:"gst registration threshold turnover composition",topic:"GST Registration & Threshold",impacts:[
{area:"GST Act",detail:"Registration mandatory if aggregate turnover exceeds Rs 40L (goods) / Rs 20L (services). Rs 20L/10L in special category states."},
{area:"Composition Scheme",detail:"Available if turnover ≤Rs 1.5 Cr (goods). Tax @1% (traders), 5% (restaurant), 6% (manufacturers). No ITC available."},
{area:"E-commerce",detail:"Mandatory registration for e-commerce operators and suppliers through e-commerce — NO threshold exemption."},
{area:"Practical Tip",detail:"Track turnover monthly. Include exempt supplies in aggregate turnover. Registration required in each state of supply."}
]},
{q:"penalty concealment 270a 271 under-reporting misreporting",topic:"Penalty — Sec 270A / 271(1)(c)",impacts:[
{area:"Income Tax",detail:"Sec 270A: Under-reporting penalty @50% of tax on under-reported income. Misreporting @200%. Replaced old 271(1)(c) from AY 2017-18."},
{area:"Key Case Law",detail:"CIT vs Reliance Petroproducts (SC): Mere making of a claim which is not sustainable does not amount to concealment. Hindustan Steel vs State of Orissa (SC): Penalty is not automatic."},
{area:"Defence",detail:"Show bona fide explanation. Disclosure in return. Due diligence in record-keeping. Invoke immunity u/s 270AA if tax + interest paid and appeal not filed."},
{area:"Practical Tip",detail:"Maintain documentary evidence for all claims. Disclose all income proactively. If notice received, respond with factual submissions within time."}
]},
{q:"80c 80d 80g deduction chapter vi savings insurance",topic:"Chapter VI-A Deductions — 80C/80D/80G",impacts:[
{area:"Income Tax",detail:"80C: Max Rs 1.5L (PPF, ELSS, NSC, tuition, housing loan principal). 80D: Rs 25K health insurance (50K for senior). 80G: Donations (100%/50%)."},
{area:"New Regime",detail:"Under 115BAC (new regime): Only Sec 80CCD(2) (NPS employer) and 80JJAA available. All other VI-A deductions NOT available."},
{area:"Form 3CD",detail:"Report in <strong>Clause 20</strong> — Verify eligibility and proof for each deduction claimed."},
{area:"Practical Tip",detail:"Complete investments before 31 March. Keep receipts/certificates. Declare to employer for TDS benefit. 80G — only digital payments."}
]},
{q:"audit 44ab tax turnover professional gross receipts",topic:"Tax Audit — Sec 44AB",impacts:[
{area:"Income Tax",detail:"Audit required if: Business turnover >Rs 1 Cr (10 Cr if cash <5%). Professional gross receipts >Rs 50L. Opted out of 44AD/ADA."},
{area:"Due Date",detail:"Tax audit report: 30 Sep. ITR for audit cases: 31 Oct. TP cases: 30 Nov."},
{area:"Penalty",detail:"Non-compliance: Penalty u/s 271B = 0.5% of turnover or Rs 1.5L, whichever is lower."},
{area:"Practical Tip",detail:"Check ALL criteria — turnover, presumptive opt-out history, partnership income. Form 3CA (company audit) vs 3CB (other audit)."}
]},
{q:"hra house rent allowance exemption 10 metro",topic:"HRA Exemption — Sec 10(13A)",impacts:[
{area:"Income Tax",detail:"Exempt: Least of (a) Actual HRA, (b) Rent paid minus 10% of salary, (c) 50% of salary (metro) / 40% (non-metro). Only in old regime."},
{area:"Form 3CD",detail:"Verify HRA exemption computation. Check rent agreement and payment proof."},
{area:"TDS Implication",detail:"Tenant (employer) must deduct TDS u/s 194IB if rent >Rs 50,000/month and individual/HUF not liable to audit."},
{area:"Practical Tip",detail:"Landlord PAN mandatory if rent >Rs 1L p.a. Keep rent receipts, bank transfer proof, rent agreement. Not available in new regime."}
]},
{q:"partnership firm partner 40b remuneration interest llp 194t",topic:"Partnership Firm — Taxation, 40(b) & TDS 194T",impacts:[
{area:"Income Tax",detail:"Remuneration to partners — Sec 40(b): Rs 6L slab at 90%, balance at 60% (FA 2024, w.e.f. AY 2025-26). Interest on capital: max 12% p.a."},
{area:"TDS",detail:"Sec 194T (w.e.f. 01.04.2025): TDS at 10% on salary/remuneration/interest/commission paid to partner if > Rs 20,000 in FY."},
{area:"IT Act 2025",detail:"Section 38 (remuneration), Section 393(3) Sl.7 (194T)."},
{area:"Form 3CD",detail:"Clause 23: Amounts admissible u/s 40(b). Clause 34: TDS compliance including 194T."},
{area:"Tax Audit",detail:"Verify partnership deed authorises remuneration. Check 40(b) limits. Verify 194T TDS deducted from April 2025."},
{area:"GST",detail:"Partnership firm is a taxable person. Profit share to partners is NOT a supply — not subject to GST. Salary/remuneration paid is also not taxable under GST."},
{area:"Practical Tip",detail:"Check if firm opts for presumptive tax (44AD/44ADA) — if yes, 40(b) deduction not available. Verify deed has remuneration clause per CBDT Circular 739/1996."}
]},
{q:"housing loan house property 24b interest home emi mortgage",topic:"Housing Loan & House Property — Sec 24(b)",impacts:[
{area:"Income Tax",detail:"Interest on housing loan: Sec 24(b) — Self-occupied: max Rs 2L; Let-out: actual interest (no limit). Pre-construction interest: 1/5th per year for 5 years."},
{area:"Deduction",detail:"Principal repayment: Sec 80C (within Rs 1.5L overall limit). Stamp duty/registration also under 80C."},
{area:"Set-off",detail:"Loss from house property: set off against other income max Rs 2L per year. Balance carried forward 8 years."},
{area:"Form 3CD",detail:"Clause 21(b): Interest disallowable u/s 36(1)(iii) if loan for business property."},
{area:"IT Act 2025",detail:"Section 30–37 (House Property), Section 103 (24(b) interest)."},
{area:"Practical Tip",detail:"Sec 80EEA: Additional Rs 1.5L for first-time buyers (loan sanctioned 01.04.2019–31.03.2022). Not available in new regime."}
]},
{q:"donation 80g charitable trust ngo 12a",topic:"Donation — Sec 80G Deduction",impacts:[
{area:"Income Tax",detail:"Sec 80G: 100% or 50% deduction depending on fund/institution. Cash donations > Rs 2,000 not eligible. Must have Form 10BE from donee."},
{area:"Compliance",detail:"Donee must be registered u/s 80G. Registration now on DARPAN portal. Form CSR-1 for Section 8 companies."},
{area:"Form 3CD",detail:"Clause 21(h): Donations not deductible u/s 80G but debited to P&L."},
{area:"IT Act 2025",detail:"Section 122 (80G equivalent)."},
{area:"New Regime",detail:"Sec 80G deduction NOT available under new tax regime."},
{area:"Practical Tip",detail:"Always verify 80G registration status on incometaxindia.gov.in before donating. Obtain Form 10BE before filing ITR."}
]},
{q:"foreign remittance 15ca 15cb tds nri non-resident 195 dtaa",topic:"Foreign Remittance — 15CA/15CB & Sec 195",impacts:[
{area:"Income Tax",detail:"Sec 195: TDS on payments to non-residents. Rate: as per DTAA or domestic rate — whichever is beneficial."},
{area:"Compliance",detail:"Form 15CA (online) and Form 15CB (CA certificate) required before remittance. Part A/B/C/D depending on amount and nature."},
{area:"Penalty",detail:"Failure to file Form 15CA: Rs 1,00,000 u/s 271-I."},
{area:"Rule 37BB",detail:"33 categories exempt from Form 15CA — listed in Schedule to Rule 37BB."},
{area:"IT Act 2025",detail:"Section 396 (Sec 195 equivalent). Section 453 (271-I equivalent)."},
{area:"Practical Tip",detail:"File Form 15CB before Part C of 15CA. AD Bank will not remit without Form 15CA. DTAA benefit requires Tax Residency Certificate (TRC) from payee."}
]},
{q:"itr income tax return filing 139 belated updated revised due date",topic:"ITR Filing — Due Dates, Late Fees & Updated Return",impacts:[
{area:"Filing",detail:"Due date: 31 July (non-audit), 31 October (audit), 30 November (TP cases). Belated return: by 31 December of AY."},
{area:"Late Fee",detail:"Sec 234F: Rs 5,000 (income > Rs 5L); Rs 1,000 (income ≤ Rs 5L); Nil (income below exemption limit)."},
{area:"Updated Return",detail:"Sec 139(8A) ITR-U: file within 48 months of AY end with additional tax of 25%/50%/60%/70%."},
{area:"Form",detail:"ITR-1 (Sahaj): Salary + 1 house + other sources ≤ Rs 50L. ITR-3: Business/Profession. ITR-4: Presumptive. Check ITR Applicability tab for full mapping."},
{area:"IT Act 2025",detail:"Section 263 (return filing). Section 263(8A) (updated return)."},
{area:"Practical Tip",detail:"Always verify Form 26AS + AIS + TIS before filing. Mismatch triggers notices u/s 143(1)(a)."}
]},
{q:"export zero rated lut igst refund shipping",topic:"Export — GST Zero-Rated & IT Provisions",impacts:[
{area:"GST",detail:"Exports are zero-rated supply u/s 16 IGST Act. Exporter can claim refund of ITC or export with payment of IGST."},
{area:"Income Tax",detail:"Export profits: no specific exemption now (Sec 10AA STPI/SEZ scheme for existing units only)."},
{area:"Compliance",detail:"LUT (Letter of Undertaking) required for export without payment of GST — file annually on GST portal."},
{area:"Form 3CD",detail:"Clause 19: Sec 10AA deduction details if applicable."},
{area:"Practical Tip",detail:"File GSTR-1 with correct export details (Table 6A). Refund claim in RFD-01. Ensure FIRC/BRC for foreign exchange receipt."}
]},
{q:"roc company compliance aoc mgt adt dir annual filing mca",topic:"ROC / Company Compliance — Annual Filings",impacts:[
{area:"Annual Filings",detail:"AOC-4 (30 days from AGM), MGT-7 (60 days from AGM), ADT-1 (15 days from AGM). Penalty Rs 100/day, no cap."},
{area:"Director KYC",detail:"DIR-3 KYC by 30 September every year. Rs 5,000 flat if missed — DIN deactivated."},
{area:"Deposits",detail:"DPT-3 by 30 June — all companies must file even if no deposits. Rs 5,000 + Rs 500/day penalty."},
{area:"MSME",detail:"MSME-1 by 30 April and 31 October (half-yearly). Rs 25,000 to Rs 3,00,000 penalty."},
{area:"Struck Off Risk",detail:"Non-filing for 3 consecutive years → Sec 248 strike-off. Directors disqualified u/s 164(2) for 5 years."},
{area:"LLP",detail:"Form 11 by 30 May, Form 8 by 30 October. Rs 100/day penalty, no cap."}
]},
{q:"tds commission brokerage 194h agent",topic:"TDS on Commission / Brokerage — Sec 194H",impacts:[
{area:"Income Tax",detail:"TDS @ 5% on commission/brokerage if > Rs 15,000 p.a. Includes insurance commission, ad commission, selling commission."},
{area:"IT Act 2025",detail:"Section 194H → Sec 408 (approx). Rate unchanged at 5%."},
{area:"Form 3CD",detail:"Report in <strong>Clause 34</strong>. Non-deduction → 30% disallowance u/s 40(a)(ia)."},
{area:"GST",detail:"Commission agent is liable for GST on commission income. If principal supplies through agent, agent issues invoice."},
{area:"Practical Tip",detail:"Distinguish from discount (trade discount not subject to 194H). Del credere commission is covered. Issue TDS certificate (Form 16A) quarterly."}
]},
{q:"tds sale property immovable 194ia land building flat",topic:"TDS on Property Sale — Sec 194-IA",impacts:[
{area:"Income Tax",detail:"Buyer deducts TDS @1% on purchase of immovable property > Rs 50 Lakh (consideration or stamp duty value, whichever higher)."},
{area:"IT Act 2025",detail:"Section 194-IA → Sec 410 (approx). Same threshold."},
{area:"Compliance",detail:"TDS via Form 26QB within 30 days from end of month. Form 16B to seller within 15 days of filing 26QB."},
{area:"Practical Tip",detail:"Agricultural land outside municipal limits is exempt. Multiple buyers/sellers: each files separate 26QB proportionately."}
]},
{q:"stamp duty circle rate 56 2 vii b gift section 50c property",topic:"Stamp Duty Value & Deemed Income — Sec 50C / 56(2)",impacts:[
{area:"Sec 50C",detail:"If sale consideration < stamp duty value by more than 10%, stamp duty value is deemed to be sale consideration for capital gains."},
{area:"Sec 56(2)(x)",detail:"Buyer: If stamp duty value exceeds purchase price by more than Rs 50,000 — difference taxable as 'Income from Other Sources'."},
{area:"Form 3CD",detail:"Verify property transactions in <strong>Clause 13-14</strong>. Check DVR/Circle Rate."},
{area:"IT Act 2025",detail:"Sec 50C → Sec 76. Sec 56(2) → Chapter XII. 10% tolerance band continues."},
{area:"Practical Tip",detail:"Safe harbour of 10% applies (Finance Act 2021). Get property valued by registered valuer if circle rate seems inflated."}
]},
{q:"section 43b 43b expense liability disallowance actually paid",topic:"Section 43B — Certain Deductions on Payment Basis",impacts:[
{area:"Income Tax",detail:"Items u/s 43B allowed ONLY if paid before return filing due date u/s 139(1): taxes/duties/cess, bonus/commission, interest to financial institution, PF/ESI/gratuity, leave encashment."},
{area:"43B(h)",detail:"MSME payments — must be within 15 days (no agreement) or agreed time (max 45 days)."},
{area:"Form 3CD",detail:"Report in <strong>Clause 26</strong> — list all Sec 43B items with due date and actual payment date."},
{area:"IT Act 2025",detail:"Section 43B → Chapter V equivalent provisions."},
{area:"Practical Tip",detail:"Accrue in March, pay before return filing due date. Track each item separately. MSME payments have no grace period — must be paid within statutory time."}
]},
{q:"tds ecommerce 194o flipkart amazon operator platform",topic:"TDS on E-Commerce — Sec 194-O",impacts:[
{area:"Income Tax",detail:"E-commerce operator deducts TDS @1% on gross amount of sale/service paid to e-commerce participant. Threshold: Nil for individuals/HUF (PAN furnished) in certain cases."},
{area:"IT Act 2025",detail:"Section 194-O → Sec 413 (approx)."},
{area:"GST",detail:"E-commerce operator also collects TCS @1% under GST Sec 52 CGST Act. So both IT TDS and GST TCS apply simultaneously."},
{area:"Practical Tip",detail:"Reconcile TDS credits in 26AS with sales reported on platforms. Both operator and seller have compliance obligations."}
]},
{q:"dividend income tds 194 shareholder company",topic:"Dividend Income & TDS — Sec 194",impacts:[
{area:"Income Tax",detail:"Dividend taxable in hands of shareholder (Finance Act 2020). TDS @10% u/s 194 if dividend > Rs 5,000 in a FY. Surcharge and cess apply."},
{area:"IT Act 2025",detail:"Section 194 → Sec 397."},
{area:"Deduction",detail:"Sec 57(i): Deduction of interest expense up to 20% of dividend income if shares held as investment (not stock-in-trade)."},
{area:"Practical Tip",detail:"File Form 15G/15H to avoid TDS if below taxable limit. For companies receiving dividend: no DDT, but intercorporate dividend may be exempt."}
]},
{q:"pan aadhaar link quoting 206aa higher rate",topic:"PAN-Aadhaar Linking & Higher TDS — Sec 206AA/206AB",impacts:[
{area:"Sec 206AA",detail:"If deductee does not furnish PAN: TDS at 20% or rate in force, whichever is higher."},
{area:"Sec 206AB",detail:"Non-filers of ITR for 2 preceding years + TDS/TCS > Rs 50,000 in each year: TDS @twice the specified rate or 5%, whichever is higher."},
{area:"PAN-Aadhaar",detail:"Inoperative PAN (not linked with Aadhaar) treated as if PAN not furnished — higher TDS applies."},
{area:"IT Act 2025",detail:"Sec 206AA → Sec 416, Sec 206AB → Sec 417."},
{area:"Practical Tip",detail:"Check compliance status on income tax portal before payment. Download non-filer list from Reporting Portal to identify 206AB cases."}
]},
{q:"crypto virtual digital asset vda 194s 2 percent",topic:"Crypto / VDA — TDS & Taxation (Sec 115BBH / 194S)",impacts:[
{area:"Income Tax",detail:"Gains from VDA taxed flat @30% (no deduction except cost of acquisition). No set-off of losses against any income. Sec 115BBH."},
{area:"TDS",detail:"Sec 194S: TDS @1% on payment for VDA if amount > Rs 50,000 (specified person) or Rs 10,000 (others)."},
{area:"Form 3CD",detail:"Verify VDA transactions, cost computation, and TDS compliance."},
{area:"IT Act 2025",detail:"Sec 115BBH → Sec 172, Sec 194S → Sec 414."},
{area:"Practical Tip",detail:"No indexation benefit. No carry forward of VDA losses. Gift of VDA taxable in hands of recipient if value > Rs 50,000."}
]},
{q:"income from other sources 56 2 gift received deemed",topic:"Income from Other Sources — Sec 56(2) / Gifts",impacts:[
{area:"Income Tax",detail:"Money > Rs 50,000 received without consideration: taxable. Property received below FMV by > Rs 50,000: difference taxable."},
{area:"Exemptions",detail:"Gifts from relatives (spouse, sibling, lineal ascendant/descendant) exempt. Also on marriage, inheritance, contemplation of death."},
{area:"IT Act 2025",detail:"Sec 56(2) → Chapter XII provisions under new Act."},
{area:"Practical Tip",detail:"Maintain gift deeds. Keep bank transfer proof. Aggregate all gifts from non-relatives per FY for Rs 50,000 threshold."}
]},
{q:"gratuity 10 10d leave encashment retirement terminal benefit",topic:"Gratuity & Leave Encashment — Exemption",impacts:[
{area:"Income Tax",detail:"Gratuity: Exempt up to Rs 25L (govt) / Rs 25L (private, Sec 10(10)) per Notification. Leave encashment: up to Rs 25L on retirement (Sec 10(10AA))."},
{area:"Sec 43B",detail:"Employer's provision for gratuity/leave: deduction only on ACTUAL PAYMENT u/s 43B(b)/(f)."},
{area:"Form 3CD",detail:"Clause 26: 43B items. Clause 21(a): Section 10 exemption claimed by employer for computation."},
{area:"IT Act 2025",detail:"Sec 10(10) → Chapter III/IV exemption; Sec 43B → Chapter V."},
{area:"Practical Tip",detail:"Rs 25 Lakh cap for gratuity raised by notification (March 2019). Keep separate gratuity and leave fund accounts."}
]},
{q:"tds non resident 195 dtaa treaty withholding nri foreign",topic:"TDS on NRI / Non-Resident — Sec 195",impacts:[
{area:"Income Tax",detail:"All payments to NR chargeable to tax require TDS u/s 195. Rate: As per Act or DTAA, whichever is beneficial. No threshold."},
{area:"Compliance",detail:"Form 15CA (online) + Form 15CB (CA cert) for foreign remittances. Lower deduction certificate u/s 197 available."},
{area:"IT Act 2025",detail:"Sec 195 → Sec 396, Sec 197 → Sec 389, Sec 271-I → Sec 453."},
{area:"Practical Tip",detail:"Obtain TRC + Form 10F from NR. Check PE (permanent establishment) risk. File Form 15CA BEFORE the bank makes the remittance."}
]},
{q:"bogus purchase sales accommodation entry hawala",topic:"Bogus Purchase / Accommodation Entry — Disallowance",impacts:[
{area:"Income Tax",detail:"If purchase found bogus: AO can add gross profit margin (typically 12.5%-25%) or disallow entire purchase. Key decisions: NK Proteins (Guj HC), Bholanath Poly Fab (Guj HC)."},
{area:"Penalty",detail:"Sec 270A misreporting penalty @200% (not 50%) if bogus claim established. Prosecution risk u/s 277."},
{area:"GST",detail:"ITC reversal mandatory. E-way bill scrutiny. GSTN analytics identifies circular trading."},
{area:"Practical Tip",detail:"Verify new vendors — GST registration status, bank details, physical existence. Keep delivery challans, weighbridge slips, transport bills."}
]},
{q:"tds transfer of property 194ia 194ib rent individual",topic:"TDS by Individual / HUF (194-IA, 194-IB, 194M, 194S)",impacts:[
{area:"194-IA",detail:"TDS @1% on immovable property > Rs 50L — buyer deducts via Form 26QB."},
{area:"194-IB",detail:"TDS @5% on rent > Rs 50,000/month if individual/HUF not liable for audit. Deposit in last month of FY or lease."},
{area:"194M",detail:"TDS @5% on commission/contractual/professional fee > Rs 50L in a FY by individual/HUF not liable for audit."},
{area:"194S",detail:"TDS @1% on virtual digital assets > Rs 50,000 (specified) / Rs 10,000 (others)."},
{area:"Practical Tip",detail:"These sections apply even to salaried individuals. Use challan-cum-statement (26QD for 194M). No TAN needed for 26QB/26QC."}
]},
{q:"agricultural income exempt farm 10 1 agriculture",topic:"Agricultural Income — Exemption & Partial Integration",impacts:[
{area:"Income Tax",detail:"Agricultural income exempt u/s 10(1). But if non-agricultural income > Rs 2.5L and agricultural income > Rs 5,000 → partial integration for rate purposes (Sec 2(1A))."},
{area:"Form 3CD",detail:"Clause 19: Exempt income credited to P&L including agricultural income."},
{area:"IT Act 2025",detail:"Sec 10(1) → exempt income schedule. Partial integration continues."},
{area:"Practical Tip",detail:"Maintain proof: land records, cultivation expenses, sale bills, mandi receipts. AO can question disproportionate agricultural income claims."}
]},
{q:"set off carry forward loss 70 71 72 73 74",topic:"Set Off & Carry Forward of Losses",impacts:[
{area:"Income Tax",detail:"Intra-head set off: automatic. Inter-head: House property loss max Rs 2L against other heads. Business loss: carry forward 8 years. Speculation loss: set off only against speculation income (4 years)."},
{area:"Capital Loss",detail:"LTCL set off only against LTCG. STCL against both STCG and LTCG. Carry forward 8 years."},
{area:"Conditions",detail:"Return must be filed before due date to carry forward (except house property loss). Sec 79: Change of shareholding >51% in closely held company → loss lapses."},
{area:"IT Act 2025",detail:"Sec 70-80 → Chapter VII (Sec 57-66)."},
{area:"Practical Tip",detail:"Maintain separate loss registers for each head and each AY. File return even if it's a loss year."}
]},
{q:"tds payment government challan 26as tds return quarterly",topic:"TDS Payment, Return & 26AS Reconciliation",impacts:[
{area:"Income Tax",detail:"TDS must be deposited by 7th of next month (30 April for March). TDS return: Q1 by 31 Jul, Q2 by 31 Oct, Q3 by 31 Jan, Q4 by 31 May."},
{area:"Penalty",detail:"Late filing fee u/s 234E: Rs 200/day (max TDS amount). Late deduction interest: 1% per month. Late deposit: 1.5% per month."},
{area:"26AS",detail:"All TDS/TCS credits appear here. AIS/TIS also shows high-value transactions. Reconcile before filing ITR."},
{area:"IT Act 2025",detail:"TDS payment/return framework → Chapter XXIII–XXIV."},
{area:"Practical Tip",detail:"Use TRACES for corrections. Download conso file for bulk correction. Match 26AS with books quarterly."}
]},
{q:"gst annual return 9 9c reconciliation statement audit",topic:"GST Annual Return (GSTR-9) & Reconciliation (9C)",impacts:[
{area:"GST",detail:"GSTR-9 (annual return) due by 31 December. GSTR-9C (self-certified reconciliation) if turnover > Rs 5 Cr."},
{area:"Form 3CD",detail:"Clause 44: GST reconciliation (GSTR-3B vs books). Differences to be reported."},
{area:"Penalty",detail:"Late GSTR-9: Rs 200/day (Rs 100 CGST + Rs 100 SGST) up to 0.5% of turnover. Interest on late tax at 18%."},
{area:"Practical Tip",detail:"Reconcile ITC in GSTR-2B vs books before filing. HSN-wise summary in Table 17/18 now mandatory. File BEFORE income tax audit completion."}
]},
{q:"gst reverse charge rcm unregistered person 9 3",topic:"GST Reverse Charge Mechanism (RCM)",impacts:[
{area:"GST",detail:"RCM applies: Sec 9(3) — notified supplies (GTA, advocate, director fees, renting by unregistered person). Sec 9(4) — procurement from unregistered person in notified categories."},
{area:"ITC",detail:"ITC available on RCM tax paid after payment is made and reflected in GSTR-3B."},
{area:"Form 3CD",detail:"Verify RCM transactions in <strong>Clause 44</strong> — GST reconciliation."},
{area:"Practical Tip",detail:"Create self-invoices for RCM transactions. GTA: option to pay GST @5% (no ITC) or 12% (full ITC). Director sitting fees always under RCM."}
]},
{q:"tcs 206c seller goods collection scrap minerals",topic:"TCS (Tax Collected at Source) — Sec 206C",impacts:[
{area:"Income Tax",detail:"TCS on sale of: scrap @1%, minerals @1%, timber/tendu @2.5%, foreign remittance @5% (above Rs 7L), motor vehicle >Rs 10L @1%."},
{area:"206C(1H)",detail:"Seller receiving > Rs 50L from a buyer: TCS @0.1% on amount exceeding Rs 50L. Not applicable if buyer is liable to TDS on goods."},
{area:"IT Act 2025",detail:"Sec 206C → Sec 418-419."},
{area:"Practical Tip",detail:"TCS credit available to buyer against tax liability. File TCS return (Form 27EQ) quarterly. Issue Form 27D."}
]},
{q:"equalisation levy google facebook digital advertising ecommerce 166",topic:"Equalisation Levy — Digital Advertising / E-Commerce",impacts:[
{area:"Income Tax",detail:"Equalisation Levy @6% on digital advertising payments to non-resident tech companies (Google, Facebook etc.) if > Rs 1 Lakh per year. E-commerce: 2% (on non-resident e-commerce operators with turnover > Rs 2 Cr — withdrawn from 01.08.2024)."},
{area:"Compliance",detail:"Deducted by payer (Indian resident). Deposited by 7th of next month. Annual return in Form 1 by 30 June."},
{area:"Form 3CD",detail:"Verify in Clause 34 — similar to TDS compliance reporting."},
{area:"Practical Tip",detail:"If EL is applicable, Sec 195 TDS does not apply (Sec 10(50) exempts EL income from IT). Check DTAA applicability first — if DTAA protects, EL may still apply as it's not a tax."}
]},
{q:"ltcg exemption 54 54ec 54f house bond reinvestment cgas",topic:"LTCG Exemptions — Sec 54 / 54EC / 54F / CGAS",impacts:[
{area:"Sec 54",detail:"LTCG on residential house: reinvest in 1 new house (or 2 if CG ≤ Rs 2 Cr, once in lifetime). Time: 1yr before/2yr after purchase, 3yr construct. Cap: Rs 10 Cr."},
{area:"Sec 54EC",detail:"LTCG on land/building: invest in NHAI/REC/PFC/IRFC bonds within 6 months. Max Rs 50L. 5-year lock-in."},
{area:"Sec 54F",detail:"LTCG on any LTCA other than house: invest in 1 house. Proportional exemption = LTCG × (cost of new house / net consideration). Must not own >1 house."},
{area:"CGAS",detail:"Capital Gains Account Scheme — deposit unutilised amount before ITR due date. Type A (savings) or Type B (term deposit). Notified banks."},
{area:"IT Act 2025",detail:"Sec 54→82, 54B→83, 54D→84, 54EC→85, 54F→87, 54G→88, 54GA→89, 54GB→90."},
{area:"Practical Tip",detail:"Use the CG + Exemption tab to plan the exact exemption, CGAS deposit, and deadline for your scenario."}
]},
{q:"mat minimum alternate tax 115jb book profit company",topic:"MAT / Minimum Alternate Tax — Sec 115JB",impacts:[
{area:"Income Tax",detail:"MAT @15% of book profit if normal tax liability < 15% of book profit. Applicable to companies. Additions/deductions per Sec 115JB(2)."},
{area:"MAT Credit",detail:"Sec 115JAA: Excess MAT paid over normal tax is MAT credit — carry forward 15 years and set off against future normal tax liability."},
{area:"Form 3CD",detail:"Clause 11: Book profit u/s 115JB with detailed computation."},
{area:"IT Act 2025",detail:"Sec 115JB → Chapter XIV equivalent (approx Sec 173-175)."},
{area:"Practical Tip",detail:"Companies under new regime (115BAA/115BAB) not liable to MAT. Maintain MAT credit register."}
]},
{q:"new regime old regime 115bac tax option exercise form 10ie",topic:"New Regime vs Old Regime — Sec 115BAC",impacts:[
{area:"Income Tax",detail:"New regime (115BAC) is default from FY 2024-25. Lower rates but no deductions/exemptions (except 80CCD(2), standard deduction Rs 75,000)."},
{area:"Rates (New)",detail:"0-4L: Nil, 4-8L: 5%, 8-12L: 10%, 12-16L: 15%, 16-20L: 20%, 20-24L: 25%, >24L: 30%. Rebate u/s 87A up to Rs 60,000 (income ≤ Rs 12L)."},
{area:"Opt Out",detail:"Business income: must opt out before due date, choice is irrevocable for that business. Salary: can choose each year via Form 10-IE/employer declaration."},
{area:"IT Act 2025",detail:"Sec 115BAC → Chapter XII, Schedule 1 (new rate structure)."},
{area:"Practical Tip",detail:"Run both regime calculations (use IT Calculator tab). If deductions > Rs 4-5L, old regime may be better. Otherwise new regime is typically better."}
]},
{q:"angel tax startup 56 2 viib share premium valuation",topic:"Angel Tax / Share Premium — Sec 56(2)(viib)",impacts:[
{area:"Income Tax",detail:"If a closely held company issues shares at premium exceeding FMV: excess is taxable as income of the company u/s 56(2)(viib)."},
{area:"Valuation",detail:"FMV determined by Rule 11UA — DCF method or NAV method. DPIIT-recognised startups exempt (until Finance Act 2023 amendments)."},
{area:"Finance Act 2024",detail:"Sec 56(2)(viib) exemption extended to ALL investors (including non-residents) w.e.f. 01.04.2024 — effectively, angel tax provisions widened then narrowed."},
{area:"Practical Tip",detail:"Get a merchant banker valuation before issuing shares at premium. DPIIT recognition is key for startups. Maintain valuation report on record."}
]},
{q:"nps national pension 80ccd deduction employer contribution",topic:"NPS — National Pension System (Sec 80CCD)",impacts:[
{area:"Income Tax",detail:"80CCD(1): Employee contribution up to 10% of salary (within Rs 1.5L of 80C). 80CCD(1B): Additional Rs 50,000 (over 80C limit). 80CCD(2): Employer contribution up to 14% (central govt) / 10% (others)."},
{area:"New Regime",detail:"Only 80CCD(2) (employer contribution) available in new regime. 80CCD(1) and 80CCD(1B) NOT available."},
{area:"IT Act 2025",detail:"Sec 80CCD → Chapter VI-B equivalent."},
{area:"Practical Tip",detail:"Employer NPS is the most tax-efficient benefit even in new regime. On maturity: 60% lump sum exempt, 40% must go to annuity (taxable as pension)."}
]}
];
function smartSearch(){
var q=document.getElementById('smartQ').value.toLowerCase().trim();
var r=document.getElementById('smartResults');
if(!q||q.length<2){r.innerHTML='<p style="text-align:center;color:var(--text-light);padding:20px;">Type at least 2 characters to search...</p>';return;}
var qWords=q.split(/\s+/);
var matches=smartDB.filter(function(item){
var keywords=item.q.split(' ');
// Match if ANY query word matches ANY keyword (partial match both ways)
return qWords.some(function(qw){
return keywords.some(function(k){return k.indexOf(qw)>=0||qw.indexOf(k)>=0;});
});
});
if(!matches.length){r.innerHTML='<p style="text-align:center;color:var(--text-light);padding:20px;">No matches found. Try keywords like: cash, TDS, MSME, depreciation, ESI, PF, rent, salary, loan, ITC</p>';return;}
r.innerHTML=matches.map(function(m){
return '<div class="card" style="margin-bottom:12px;"><h3 style="color:var(--accent);margin-bottom:10px;">'+m.topic+'</h3><table class="limits-table"><thead><tr><th style="width:120px;">Area</th><th>Impact / Requirement</th></tr></thead><tbody>'+m.impacts.map(function(i){return '<tr><td><strong>'+i.area+'</strong></td><td style="font-size:0.85rem;">'+i.detail+'</td></tr>';}).join('')+'</tbody></table></div>';
}).join('');
}

// ==================== DROPDOWN POPULATION ====================
function populateSmartDropdown(){
  var dd=document.getElementById('smartDropdown');
  if(!dd)return;
  smartDB.sort(function(a,b){return a.topic.localeCompare(b.topic);});
  smartDB.forEach(function(item,idx){
    var opt=document.createElement('option');
    opt.value=idx;
    opt.textContent=item.topic;
    dd.appendChild(opt);
  });
}
function smartDropdownSelect(){
  var dd=document.getElementById('smartDropdown');
  var idx=parseInt(dd.value,10);
  if(isNaN(idx))return;
  var item=smartDB[idx];
  if(!item)return;
  // Clear text search to avoid confusion
  document.getElementById('smartQ').value='';
  var r=document.getElementById('smartResults');
  r.innerHTML='<div class="card" style="margin-bottom:12px;"><h3 style="color:var(--accent);margin-bottom:10px;">'+item.topic+'</h3><table class="limits-table"><thead><tr><th style="width:120px;">Area</th><th>Impact / Requirement</th></tr></thead><tbody>'+item.impacts.map(function(i){return '<tr><td><strong>'+i.area+'</strong></td><td style="font-size:0.85rem;">'+i.detail+'</td></tr>';}).join('')+'</tbody></table></div>';
}
populateSmartDropdown();

