// One-shot splitter: index.html → css/styles.css + js/*.js + new index.html
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const src = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const lines = src.split(/\r?\n/);
// 1-indexed slice helper (inclusive)
const slice = (a, b) => lines.slice(a - 1, b).join('\n');

// ---- CSS ----
const css = slice(11, 227) + '\n\n' + slice(233, 234) + '\n';
fs.writeFileSync(path.join(ROOT, 'css', 'styles.css'), css);

// ---- JS files: ranges chosen by tracing function/section boundaries ----
const ranges = {
  // calculators: EMI, IT calc, Depreciation IT, Depreciation Co, Capital Gains, Interest 234, Impact, Refund
  'calculators.js': [
    [2351, 2450],
    [2535, 2552],
    [3019, 3046],
    [3261, 3384],
    [3385, 3460],
    [3461, 3522],
    [4596, 4655],
  ],
  // gst: GST Rates, GST Registration
  'gst.js': [
    [2553, 2591],
    [4547, 4595],
  ],
  // audit: 3CD Clauses, MSME, Notice, CARO, Audit Checklist, AS
  'audit.js': [
    [2452, 2533],
    [3047, 3059],
    [3060, 3102],
    [3103, 3124],
    [3125, 3180],
    [3181, 3260],
  ],
  // compliance: Section Mapping, ITR Form, Compliance Calendar, 15CA, Rule37BB, Penalties, Partnership, ITR-U, Presumptive, ROC
  'compliance.js': [
    [2592, 3018],
    [3729, 3875],
    [3876, 4094],
    [4095, 4143],
    [4144, 4199],
    [4200, 4244],
    [4245, 4351],
    [4352, 4432],
    [4433, 4546],
    [4656, 4744],
  ],
  // smartsearch: smartDB + smartSearch
  'smartsearch.js': [
    [3523, 3728],
  ],
  // main: utility (switchTab, fmt, escapeHTML) + init code (footer auto-add, mobile wrap, back-to-top)
  // Note: main.js loads LAST so init code can call functions defined in other files
  'main.js': [
    [2344, 2349],
    [4745, 4787],
  ],
};

const headerFor = (name) => `// js/${name} — extracted from index.html\n// Generated by split.cjs\n\n`;

for (const [name, parts] of Object.entries(ranges)) {
  let body = headerFor(name);
  for (const [a, b] of parts) {
    body += slice(a, b) + '\n\n';
  }
  fs.writeFileSync(path.join(ROOT, 'js', name), body);
}

// ---- New index.html ----
// Keep: 1-9 (head), insert <link>, then 229-231 (close head, open body), skip 232-235 (small style),
// then 236-2342 (body + jsPDF CDN), insert new <script> tags, then 4789-4791 (closing tags)
const newHtml = [
  slice(1, 9),
  '    <link rel="stylesheet" href="css/styles.css">',
  slice(229, 231),
  slice(236, 2342),
  '<script src="js/calculators.js"></script>',
  '<script src="js/gst.js"></script>',
  '<script src="js/audit.js"></script>',
  '<script src="js/compliance.js"></script>',
  '<script src="js/smartsearch.js"></script>',
  '<script src="js/main.js"></script>',
  slice(4790, 4791),
].join('\n') + '\n';

fs.writeFileSync(path.join(ROOT, 'index.html.new'), newHtml);

console.log('CSS:', fs.statSync(path.join(ROOT,'css','styles.css')).size, 'bytes');
for (const name of Object.keys(ranges)) {
  console.log('JS', name+':', fs.statSync(path.join(ROOT,'js',name)).size, 'bytes');
}
console.log('New index.html.new:', fs.statSync(path.join(ROOT,'index.html.new')).size, 'bytes');
